'use strict';

module.exports = [
  {
    "price": 495,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 3000",
    "memory": 128,
    "ram": 64,
    "usb3": 4,
    "usb2": 1,
    "coresNumber": 1,
    "diagonal": 18.6,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "black",
    "model": "MEDIA CENTER 1574",
    "mark": "DEXP"
  },
  {
    "price": 1150,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 128,
    "ram": 2,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 2,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "y580",
    "mark": "Acer"
  },
  {
    "price": 725,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 8192,
    "ram": 2,
    "usb3": 4,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 13.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "white",
    "model": "Mac mini",
    "mark": "Acer"
  },
  {
    "price": 940,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 1024,
    "ram": 64,
    "usb3": 3,
    "usb2": 1,
    "coresNumber": 4,
    "diagonal": 13.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "green",
    "model": "IdeaPad",
    "mark": "Acer"
  },
  {
    "price": 580,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 1024,
    "ram": 2,
    "usb3": 4,
    "usb2": 3,
    "coresNumber": 1,
    "diagonal": 13.7,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "orange",
    "model": "Surface",
    "mark": "MSI"
  },
  {
    "price": 495,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 4000",
    "memory": 512,
    "ram": 1,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 1,
    "diagonal": 17.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "white",
    "model": "Z800",
    "mark": "ASUS"
  },
  {
    "price": 780,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 256,
    "ram": 16,
    "usb3": 0,
    "usb2": 3,
    "coresNumber": 8,
    "diagonal": 17.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "red",
    "model": "GX-700",
    "mark": "Apple"
  },
  {
    "price": 860,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 128,
    "ram": 2,
    "usb3": 2,
    "usb2": 2,
    "coresNumber": 16,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "GL552VW-DM321T",
    "mark": "Lenovo"
  },
  {
    "price": 1280,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 4000",
    "memory": 8192,
    "ram": 32,
    "usb3": 4,
    "usb2": 3,
    "coresNumber": 1,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "purple",
    "model": "Zenbook Pro",
    "mark": "Toshiba"
  },
  {
    "price": 460,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 4000",
    "memory": 512,
    "ram": 2,
    "usb3": 0,
    "usb2": 0,
    "coresNumber": 1,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "purple",
    "model": "Mac mini",
    "mark": "DEXP"
  },
  {
    "price": 1020,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 64,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 2048,
    "ram": 8,
    "usb3": 2,
    "usb2": 0,
    "coresNumber": 1,
    "diagonal": 13.3,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "purple",
    "model": "GX-700",
    "mark": "Acer"
  },
  {
    "price": 670,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 8,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 512,
    "ram": 16,
    "usb3": 4,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 11.1,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "white",
    "model": "Zenbook Pro",
    "mark": "Lenovo"
  },
  {
    "price": 760,
    "operatingSystem": "Linux",
    "processor": "AMD",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 1024,
    "ram": 2,
    "usb3": 2,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 18.6,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "black",
    "model": "EeeBook",
    "mark": "Lenovo"
  },
  {
    "price": 850,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 3000",
    "memory": 2048,
    "ram": 8,
    "usb3": 1,
    "usb2": 2,
    "coresNumber": 1,
    "diagonal": 17.3,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "black",
    "model": "DM036T",
    "mark": "MSI"
  },
  {
    "price": 495,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 4096,
    "ram": 4,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 15.6,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "9F4-5",
    "mark": "MSI"
  },
  {
    "price": 495,
    "operatingSystem": "Linux",
    "processor": "AMD",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 512,
    "ram": 64,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 4,
    "diagonal": 15.6,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "orange",
    "model": "IdeaPad",
    "mark": "Acer"
  },
  {
    "price": 920,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 8192,
    "ram": 4,
    "usb3": 1,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 15.6,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "blue",
    "model": "y580",
    "mark": "Toshiba"
  },
  {
    "price": 670,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 2048,
    "ram": 32,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 2,
    "diagonal": 18.6,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "y580",
    "mark": "DEXP"
  },
  {
    "price": 460,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 4096,
    "ram": 16,
    "usb3": 1,
    "usb2": 3,
    "coresNumber": 1,
    "diagonal": 13.3,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "grey",
    "model": "DM036T",
    "mark": "Apple"
  },
  {
    "price": 760,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 64,
    "videocard": "Intel HD Graphics 3000",
    "memory": 2048,
    "ram": 64,
    "usb3": 1,
    "usb2": 1,
    "coresNumber": 1,
    "diagonal": 20.1,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "white",
    "model": "y580",
    "mark": "Acer"
  },
  {
    "price": 380,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 64,
    "videocard": "Intel HD Graphics 4000",
    "memory": 256,
    "ram": 8,
    "usb3": 1,
    "usb2": 3,
    "coresNumber": 4,
    "diagonal": 13.3,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "red",
    "model": "Surface",
    "mark": "Toshiba"
  },
  {
    "price": 340,
    "operatingSystem": "Linux",
    "processor": "AMD",
    "videomemory": 64,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 512,
    "ram": 8,
    "usb3": 4,
    "usb2": 1,
    "coresNumber": 16,
    "diagonal": 14,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "MEDIA CENTER 1574",
    "mark": "Apple"
  },
  {
    "price": 1280,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 4096,
    "ram": 4,
    "usb3": 4,
    "usb2": 1,
    "coresNumber": 16,
    "diagonal": 17.3,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "purple",
    "model": "Surface",
    "mark": "DEXP"
  },
  {
    "price": 1280,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 8192,
    "ram": 16,
    "usb3": 1,
    "usb2": 3,
    "coresNumber": 8,
    "diagonal": 13.7,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "EeeBook",
    "mark": "DEXP"
  },
  {
    "price": 560,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 8,
    "videocard": "Intel HD Graphics 3000",
    "memory": 8192,
    "ram": 1,
    "usb3": 2,
    "usb2": 1,
    "coresNumber": 2,
    "diagonal": 17.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "red",
    "model": "9F4-5",
    "mark": "HP"
  },
  {
    "price": 380,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 8,
    "videocard": "Intel HD Graphics 4000",
    "memory": 8192,
    "ram": 16,
    "usb3": 0,
    "usb2": 1,
    "coresNumber": 16,
    "diagonal": 18.6,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "white",
    "model": "GAMER 1748",
    "mark": "Apple"
  },
  {
    "price": 725,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 4096,
    "ram": 1,
    "usb3": 2,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 17.1,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "6QE-053",
    "mark": "Lenovo"
  },
  {
    "price": 640,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 4096,
    "ram": 4,
    "usb3": 1,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 17.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "optima",
    "mark": "DEXP"
  },
  {
    "price": 760,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 64,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 128,
    "ram": 1,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 4,
    "diagonal": 11.1,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "green",
    "model": "6QE-053",
    "mark": "ASUS"
  },
  {
    "price": 640,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 32,
    "videocard": "Intel HD Graphics 4000",
    "memory": 512,
    "ram": 16,
    "usb3": 4,
    "usb2": 0,
    "coresNumber": 1,
    "diagonal": 11.1,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "black",
    "model": "6QE-053",
    "mark": "Apple"
  },
  {
    "price": 560,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 2048,
    "ram": 1,
    "usb3": 3,
    "usb2": 0,
    "coresNumber": 4,
    "diagonal": 13.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "blue",
    "model": "Surface",
    "mark": "Lenovo"
  },
  {
    "price": 420,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 4000",
    "memory": 8192,
    "ram": 64,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 16,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "purple",
    "model": "Surface",
    "mark": "MSI"
  },
  {
    "price": 495,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 3000",
    "memory": 512,
    "ram": 8,
    "usb3": 2,
    "usb2": 2,
    "coresNumber": 2,
    "diagonal": 15.6,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "violet",
    "model": "MEDIA CENTER 1574",
    "mark": "DEXP"
  },
  {
    "price": 840,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 2048,
    "ram": 16,
    "usb3": 3,
    "usb2": 0,
    "coresNumber": 8,
    "diagonal": 17.1,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "y580",
    "mark": "Apple"
  },
  {
    "price": 640,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 3000",
    "memory": 2048,
    "ram": 64,
    "usb3": 0,
    "usb2": 2,
    "coresNumber": 16,
    "diagonal": 13.7,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "blue",
    "model": "GAMER 1748",
    "mark": "Apple"
  },
  {
    "price": 460,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 16,
    "videocard": "Intel HD Graphics 4000",
    "memory": 512,
    "ram": 64,
    "usb3": 2,
    "usb2": 3,
    "coresNumber": 8,
    "diagonal": 11.3,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "Surface",
    "mark": "Sony"
  },
  {
    "price": 1280,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 128,
    "ram": 2,
    "usb3": 0,
    "usb2": 1,
    "coresNumber": 4,
    "diagonal": 17.3,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "black",
    "model": "Surface",
    "mark": "Toshiba"
  },
  {
    "price": 530,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 8192,
    "ram": 8,
    "usb3": 1,
    "usb2": 1,
    "coresNumber": 8,
    "diagonal": 14,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "GL552VW-DM321T",
    "mark": "Sony"
  },
  {
    "price": 560,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 4,
    "videocard": "Intel HD Graphics 4000",
    "memory": 8192,
    "ram": 16,
    "usb3": 4,
    "usb2": 0,
    "coresNumber": 4,
    "diagonal": 11.1,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "green",
    "model": "GX-700",
    "mark": "Sony"
  },
  {
    "price": 780,
    "operatingSystem": "Linux",
    "processor": "AMD",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 3000",
    "memory": 1024,
    "ram": 32,
    "usb3": 3,
    "usb2": 1,
    "coresNumber": 1,
    "diagonal": 15.6,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "GX-700",
    "mark": "Acer"
  },
  {
    "price": 725,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 64,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 8192,
    "ram": 64,
    "usb3": 1,
    "usb2": 0,
    "coresNumber": 4,
    "diagonal": 17.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": "Surface",
    "mark": "DEXP"
  },
  {
    "price": 300,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 3000",
    "memory": 256,
    "ram": 1,
    "usb3": 0,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 13.3,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "green",
    "model": "GAMER 1748",
    "mark": "Apple"
  },
  {
    "price": 840,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 3000",
    "memory": 1024,
    "ram": 16,
    "usb3": 3,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 17.3,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "DM036T",
    "mark": "HP"
  },
  {
    "price": 940,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 256,
    "ram": 16,
    "usb3": 0,
    "usb2": 2,
    "coresNumber": 1,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "grey",
    "model": "9F4-5",
    "mark": "Acer"
  },
  {
    "price": 670,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 8,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 2048,
    "ram": 8,
    "usb3": 3,
    "usb2": 1,
    "coresNumber": 8,
    "diagonal": 14,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "Redhost",
    "mark": "Lenovo"
  },
  {
    "price": 760,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 128,
    "ram": 4,
    "usb3": 4,
    "usb2": 1,
    "coresNumber": 2,
    "diagonal": 11.1,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "blue",
    "model": "6QE-053",
    "mark": "HP"
  },
  {
    "price": 780,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 128,
    "ram": 16,
    "usb3": 2,
    "usb2": 2,
    "coresNumber": 8,
    "diagonal": 17.1,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "white",
    "model": "EeeBook",
    "mark": "Acer"
  },
  {
    "price": 300,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 256,
    "ram": 4,
    "usb3": 3,
    "usb2": 1,
    "coresNumber": 8,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "yellow",
    "model": "GL552VW-DM321T",
    "mark": "MSI"
  },
  {
    "price": 850,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 4000",
    "memory": 128,
    "ram": 2,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 8,
    "diagonal": 15.6,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "grey",
    "model": "9F4-5",
    "mark": "Dell"
  },
  {
    "price": 670,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 4000",
    "memory": 128,
    "ram": 32,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 8,
    "diagonal": 11.1,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "Surface",
    "mark": "Dell"
  },
  {
    "price": 495,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 256,
    "ram": 4,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 16,
    "diagonal": 11.3,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "violet",
    "model": "DM036T",
    "mark": "Lenovo"
  },
  {
    "price": 300,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 16,
    "videocard": "Intel HD Graphics 3000",
    "memory": 128,
    "ram": 2,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 2,
    "diagonal": 14,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "grey",
    "model": "Mac Pro",
    "mark": "Toshiba"
  },
  {
    "price": 920,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 4096,
    "ram": 64,
    "usb3": 1,
    "usb2": 1,
    "coresNumber": 2,
    "diagonal": 17.1,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "violet",
    "model": "IdeaPad",
    "mark": "ASUS"
  },
  {
    "price": 780,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 3000",
    "memory": 8192,
    "ram": 16,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 8,
    "diagonal": 17.1,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "6QE-053",
    "mark": "MSI"
  },
  {
    "price": 840,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 8192,
    "ram": 16,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 1,
    "diagonal": 17.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "blue",
    "model": "DM036T",
    "mark": "Toshiba"
  },
  {
    "price": 1280,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 4096,
    "ram": 64,
    "usb3": 3,
    "usb2": 1,
    "coresNumber": 1,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "purple",
    "model": "6QE-053",
    "mark": "Apple"
  },
  {
    "price": 1020,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 4,
    "videocard": "Intel HD Graphics 3000",
    "memory": 8192,
    "ram": 16,
    "usb3": 2,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "blue",
    "model": "GL552VW-DM321T",
    "mark": "DEXP"
  },
  {
    "price": 780,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 128,
    "ram": 16,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 15.6,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "optima",
    "mark": "Apple"
  },
  {
    "price": 1280,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 4096,
    "ram": 4,
    "usb3": 2,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 11.1,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "blue",
    "model": "9F4-5",
    "mark": "Lenovo"
  },
  {
    "price": 510,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 8192,
    "ram": 8,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 4,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "MEDIA CENTER 1574",
    "mark": "Apple"
  },
  {
    "price": 860,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 2048,
    "ram": 64,
    "usb3": 4,
    "usb2": 3,
    "coresNumber": 4,
    "diagonal": 13.7,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": "GAMER 1748",
    "mark": "HP"
  },
  {
    "price": 380,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 8192,
    "ram": 64,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 16,
    "diagonal": 17.1,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "green",
    "model": "optima",
    "mark": "ASUS"
  },
  {
    "price": 530,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 8192,
    "ram": 2,
    "usb3": 0,
    "usb2": 2,
    "coresNumber": 2,
    "diagonal": 17.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "black",
    "model": "6QE-053",
    "mark": "Sony"
  },
  {
    "price": 780,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 16,
    "videocard": "Intel HD Graphics 4000",
    "memory": 1024,
    "ram": 64,
    "usb3": 3,
    "usb2": 3,
    "coresNumber": 2,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "violet",
    "model": "GL552VW-DM321T",
    "mark": "Sony"
  },
  {
    "price": 560,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 8,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 128,
    "ram": 8,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 14,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "GL552VW-DM321T",
    "mark": "Toshiba"
  },
  {
    "price": 940,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 32,
    "videocard": "Intel HD Graphics 3000",
    "memory": 8192,
    "ram": 16,
    "usb3": 4,
    "usb2": 1,
    "coresNumber": 1,
    "diagonal": 11.3,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "grey",
    "model": "GX-700",
    "mark": "Lenovo"
  },
  {
    "price": 560,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 16,
    "videocard": "Intel HD Graphics 4000",
    "memory": 8192,
    "ram": 8,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 18.6,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "DM036T",
    "mark": "MSI"
  },
  {
    "price": 840,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 32,
    "videocard": "Intel HD Graphics 4000",
    "memory": 8192,
    "ram": 64,
    "usb3": 1,
    "usb2": 2,
    "coresNumber": 16,
    "diagonal": 20.1,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": "MEDIA CENTER 1574",
    "mark": "Acer"
  },
  {
    "price": 580,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 3000",
    "memory": 8192,
    "ram": 64,
    "usb3": 0,
    "usb2": 3,
    "coresNumber": 16,
    "diagonal": 13.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "red",
    "model": "MEDIA CENTER 1574",
    "mark": "HP"
  },
  {
    "price": 850,
    "operatingSystem": "Linux",
    "processor": "AMD",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 2048,
    "ram": 4,
    "usb3": 1,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "GX-700",
    "mark": "HP"
  },
  {
    "price": 300,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 16,
    "videocard": "Intel HD Graphics 4000",
    "memory": 4096,
    "ram": 64,
    "usb3": 1,
    "usb2": 0,
    "coresNumber": 1,
    "diagonal": 11.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "white",
    "model": "y580",
    "mark": "DEXP"
  },
  {
    "price": 670,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 8,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 1024,
    "ram": 16,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 15.6,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "red",
    "model": "Zenbook Pro",
    "mark": "Sony"
  },
  {
    "price": 1280,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 256,
    "ram": 64,
    "usb3": 4,
    "usb2": 3,
    "coresNumber": 4,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "Zenbook Pro",
    "mark": "Dell"
  },
  {
    "price": 840,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 16,
    "videocard": "Intel HD Graphics 3000",
    "memory": 8192,
    "ram": 4,
    "usb3": 4,
    "usb2": 3,
    "coresNumber": 2,
    "diagonal": 20.1,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "9F4-5",
    "mark": "Acer"
  },
  {
    "price": 850,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 256,
    "ram": 8,
    "usb3": 0,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 17.3,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "GX-700",
    "mark": "HP"
  },
  {
    "price": 300,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 4,
    "videocard": "Intel HD Graphics 3000",
    "memory": 512,
    "ram": 1,
    "usb3": 3,
    "usb2": 0,
    "coresNumber": 8,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "red",
    "model": "Zenbook Pro",
    "mark": "HP"
  },
  {
    "price": 725,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "Intel HD Graphics 4000",
    "memory": 1024,
    "ram": 16,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 2,
    "diagonal": 13.3,
    "isLaptop": false,
    "wifi": "802.11c",
    "color": "yellow",
    "model": "MEDIA CENTER 1574",
    "mark": "Toshiba"
  },
  {
    "price": 420,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 4096,
    "ram": 2,
    "usb3": 0,
    "usb2": 3,
    "coresNumber": 16,
    "diagonal": 14,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "black",
    "model": "optima",
    "mark": "Acer"
  },
  {
    "price": 840,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 4000",
    "memory": 128,
    "ram": 1,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 16,
    "diagonal": 17.3,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "white",
    "model": "Redhost",
    "mark": "ASUS"
  },
  {
    "price": 840,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 64,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 4096,
    "ram": 1,
    "usb3": 4,
    "usb2": 1,
    "coresNumber": 8,
    "diagonal": 14,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "green",
    "model": "DM036T",
    "mark": "Lenovo"
  },
  {
    "price": 460,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 2048,
    "ram": 32,
    "usb3": 0,
    "usb2": 0,
    "coresNumber": 1,
    "diagonal": 18.6,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "orange",
    "model": "9F4-5",
    "mark": "Apple"
  },
  {
    "price": 670,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 1024,
    "ram": 64,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 8,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "green",
    "model": "DM036T",
    "mark": "ASUS"
  },
  {
    "price": 940,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 16,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 256,
    "ram": 64,
    "usb3": 3,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 18.6,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "orange",
    "model": "optima",
    "mark": "HP"
  },
  {
    "price": 725,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 1024,
    "ram": 4,
    "usb3": 1,
    "usb2": 0,
    "coresNumber": 1,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "black",
    "model": "9F4-5",
    "mark": "Sony"
  },
  {
    "price": 860,
    "operatingSystem": "Windows",
    "processor": "Intel",
    "videomemory": 64,
    "videocard": "Intel HD Graphics 3000",
    "memory": 1024,
    "ram": 2,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 1,
    "diagonal": 18.6,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "violet",
    "model": "Mac mini",
    "mark": "ASUS"
  },
  {
    "price": 850,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 8,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 2048,
    "ram": 64,
    "usb3": 1,
    "usb2": 0,
    "coresNumber": 8,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "DM036T",
    "mark": "MSI"
  },
  {
    "price": 640,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 2,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 1024,
    "ram": 8,
    "usb3": 2,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 15.6,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "violet",
    "model": "DM036T",
    "mark": "Toshiba"
  },
  {
    "price": 940,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 512,
    "ram": 64,
    "usb3": 1,
    "usb2": 2,
    "coresNumber": 1,
    "diagonal": 13.3,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "red",
    "model": "Mac Pro",
    "mark": "HP"
  },
  {
    "price": 780,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 8,
    "videocard": "Intel HD Graphics 4000",
    "memory": 8192,
    "ram": 8,
    "usb3": 2,
    "usb2": 0,
    "coresNumber": 1,
    "diagonal": 17.1,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "MEDIA CENTER 1574",
    "mark": "ASUS"
  },
  {
    "price": 860,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 8,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 512,
    "ram": 2,
    "usb3": 1,
    "usb2": 1,
    "coresNumber": 1,
    "diagonal": 11.3,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "white",
    "model": "GX-700",
    "mark": "HP"
  },
  {
    "price": 380,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 4096,
    "ram": 1,
    "usb3": 2,
    "usb2": 2,
    "coresNumber": 8,
    "diagonal": 20.1,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "DM036T",
    "mark": "Apple"
  },
  {
    "price": 920,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 4,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 4096,
    "ram": 2,
    "usb3": 2,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 18.6,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "green",
    "model": "Zenbook Pro",
    "mark": "Dell"
  },
  {
    "price": 495,
    "operatingSystem": "Linux",
    "processor": "Mac",
    "videomemory": 64,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 256,
    "ram": 64,
    "usb3": 3,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 20.1,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "GL552VW-DM321T",
    "mark": "Acer"
  },
  {
    "price": 760,
    "operatingSystem": "Windows",
    "processor": "Mac",
    "videomemory": 32,
    "videocard": "Intel HD Graphics 4000",
    "memory": 4096,
    "ram": 8,
    "usb3": 4,
    "usb2": 3,
    "coresNumber": 1,
    "diagonal": 14,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "black",
    "model": "GL552VW-DM321T",
    "mark": "Toshiba"
  },
  {
    "price": 840,
    "operatingSystem": "Mac OS X",
    "processor": "AMD",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 1024,
    "ram": 16,
    "usb3": 2,
    "usb2": 1,
    "coresNumber": 1,
    "diagonal": 14,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "yellow",
    "model": "IdeaPad",
    "mark": "DEXP"
  },
  {
    "price": 460,
    "operatingSystem": "Mac OS X",
    "processor": "Intel",
    "videomemory": 32,
    "videocard": "Intel HD Graphics 3000",
    "memory": 128,
    "ram": 64,
    "usb3": 4,
    "usb2": 3,
    "coresNumber": 16,
    "diagonal": 20.1,
    "isLaptop": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "GAMER 1748",
    "mark": "Toshiba"
  },
  {
    "price": 1500,
    "operatingSystem": "Mac OS X",
    "processor": "Mac",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 640",
    "memory": 1024,
    "ram": 64,
    "usb3": 3,
    "usb2": 2,
    "coresNumber": 4,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11ac",
    "color": "orange",
    "model": "GX-700",
    "mark": "Sony"
  },
  {
    "price": 1500,
    "operatingSystem": "Linux",
    "processor": "Intel",
    "videomemory": 1,
    "videocard": "NVidia GeForce GTX 730",
    "memory": 8192,
    "ram": 2,
    "usb3": 3,
    "usb2": 0,
    "coresNumber": 2,
    "diagonal": 13.3,
    "isLaptop": true,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "optima",
    "mark": "MSI"
  },
  {
    "price": 580,
    "operatingSystem": "Windows",
    "processor": "AMD",
    "videomemory": 32,
    "videocard": "NVidia GeForce GTX 950",
    "memory": 256,
    "ram": 32,
    "usb3": 4,
    "usb2": 2,
    "coresNumber": 2,
    "diagonal": 13.7,
    "isLaptop": true,
    "wifi": "802.11c",
    "color": "purple",
    "model": "DM036T",
    "mark": "Toshiba"
  },
  {
    "price": 1500,
    "operatingSystem": "Linux",
    "processor": "AMD",
    "videomemory": 2,
    "videocard": "Intel HD Graphics 3000",
    "memory": 128,
    "ram": 1,
    "usb3": 1,
    "usb2": 2,
    "coresNumber": 8,
    "diagonal": 11.3,
    "isLaptop": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "6QE-053",
    "mark": "Apple"
  },
  {
    "mark": "DEXP",
    "model": "MEDIA CENTER 1574",
    "color": "black",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 18.6,
    "coresNumber": 1,
    "usb2": 1,
    "usb3": 4,
    "ram": 64,
    "memory": 128,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 2,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 495
  },
  {
    "mark": "Acer",
    "model": "y580",
    "color": "blue",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 2,
    "usb2": 3,
    "usb3": 3,
    "ram": 2,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 16,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 1150
  },
  {
    "mark": "Acer",
    "model": "Mac mini",
    "color": "white",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 13.3,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 4,
    "ram": 2,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 4,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 725
  },
  {
    "mark": "Acer",
    "model": "IdeaPad",
    "color": "green",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 13.3,
    "coresNumber": 4,
    "usb2": 1,
    "usb3": 3,
    "ram": 64,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 16,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 940
  },
  {
    "mark": "MSI",
    "model": "Surface",
    "color": "orange",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 13.7,
    "coresNumber": 1,
    "usb2": 3,
    "usb3": 4,
    "ram": 2,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 580
  },
  {
    "mark": "ASUS",
    "model": "Z800",
    "color": "white",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 17.1,
    "coresNumber": 1,
    "usb2": 2,
    "usb3": 3,
    "ram": 1,
    "memory": 512,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 1,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 495
  },
  {
    "mark": "Apple",
    "model": "GX-700",
    "color": "red",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 17.3,
    "coresNumber": 8,
    "usb2": 3,
    "usb3": 0,
    "ram": 16,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 16,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 780
  },
  {
    "mark": "Lenovo",
    "model": "GL552VW-DM321T",
    "color": "orange",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 16,
    "usb2": 2,
    "usb3": 2,
    "ram": 2,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 4,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 860
  },
  {
    "mark": "Toshiba",
    "model": "Zenbook Pro",
    "color": "purple",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 1,
    "usb2": 3,
    "usb3": 4,
    "ram": 32,
    "memory": 8192,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 1,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 1280
  },
  {
    "mark": "DEXP",
    "model": "Mac mini",
    "color": "purple",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 1,
    "usb2": 0,
    "usb3": 0,
    "ram": 2,
    "memory": 512,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 2,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 460
  },
  {
    "mark": "Acer",
    "model": "GX-700",
    "color": "purple",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 13.3,
    "coresNumber": 1,
    "usb2": 0,
    "usb3": 2,
    "ram": 8,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 64,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 1020
  },
  {
    "mark": "Lenovo",
    "model": "Zenbook Pro",
    "color": "white",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 11.1,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 4,
    "ram": 16,
    "memory": 512,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 8,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 670
  },
  {
    "mark": "Lenovo",
    "model": "EeeBook",
    "color": "black",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 18.6,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 2,
    "ram": 2,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 4,
    "processor": "AMD",
    "operatingSystem": "Linux",
    "price": 760
  },
  {
    "mark": "MSI",
    "model": "DM036T",
    "color": "black",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 17.3,
    "coresNumber": 1,
    "usb2": 2,
    "usb3": 1,
    "ram": 8,
    "memory": 2048,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 2,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 850
  },
  {
    "mark": "MSI",
    "model": "9F4-5",
    "color": "yellow",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 15.6,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 3,
    "ram": 4,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 16,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 495
  },
  {
    "mark": "Acer",
    "model": "IdeaPad",
    "color": "orange",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 15.6,
    "coresNumber": 4,
    "usb2": 3,
    "usb3": 3,
    "ram": 64,
    "memory": 512,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 2,
    "processor": "AMD",
    "operatingSystem": "Linux",
    "price": 495
  },
  {
    "mark": "Toshiba",
    "model": "y580",
    "color": "blue",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 15.6,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 1,
    "ram": 4,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 920
  },
  {
    "mark": "DEXP",
    "model": "y580",
    "color": "grey",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 18.6,
    "coresNumber": 2,
    "usb2": 2,
    "usb3": 3,
    "ram": 32,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 16,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 670
  },
  {
    "mark": "Apple",
    "model": "DM036T",
    "color": "grey",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 13.3,
    "coresNumber": 1,
    "usb2": 3,
    "usb3": 1,
    "ram": 16,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 32,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 460
  },
  {
    "mark": "Acer",
    "model": "y580",
    "color": "white",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 20.1,
    "coresNumber": 1,
    "usb2": 1,
    "usb3": 1,
    "ram": 64,
    "memory": 2048,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 64,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 760
  },
  {
    "mark": "Toshiba",
    "model": "Surface",
    "color": "red",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 13.3,
    "coresNumber": 4,
    "usb2": 3,
    "usb3": 1,
    "ram": 8,
    "memory": 256,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 64,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 380
  },
  {
    "mark": "Apple",
    "model": "MEDIA CENTER 1574",
    "color": "red",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 14,
    "coresNumber": 16,
    "usb2": 1,
    "usb3": 4,
    "ram": 8,
    "memory": 512,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 64,
    "processor": "AMD",
    "operatingSystem": "Linux",
    "price": 340
  },
  {
    "mark": "DEXP",
    "model": "Surface",
    "color": "purple",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 17.3,
    "coresNumber": 16,
    "usb2": 1,
    "usb3": 4,
    "ram": 4,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 32,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 1280
  },
  {
    "mark": "DEXP",
    "model": "EeeBook",
    "color": "grey",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 13.7,
    "coresNumber": 8,
    "usb2": 3,
    "usb3": 1,
    "ram": 16,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 1,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 1280
  },
  {
    "mark": "HP",
    "model": "9F4-5",
    "color": "red",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 17.3,
    "coresNumber": 2,
    "usb2": 1,
    "usb3": 2,
    "ram": 1,
    "memory": 8192,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 8,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 560
  },
  {
    "mark": "Apple",
    "model": "GAMER 1748",
    "color": "white",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 18.6,
    "coresNumber": 16,
    "usb2": 1,
    "usb3": 0,
    "ram": 16,
    "memory": 8192,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 8,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 380
  },
  {
    "mark": "Lenovo",
    "model": "6QE-053",
    "color": "purple",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 17.1,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 2,
    "ram": 1,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 725
  },
  {
    "mark": "DEXP",
    "model": "optima",
    "color": "black",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 17.1,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 1,
    "ram": 4,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 4,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 640
  },
  {
    "mark": "ASUS",
    "model": "6QE-053",
    "color": "green",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 11.1,
    "coresNumber": 4,
    "usb2": 3,
    "usb3": 3,
    "ram": 1,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 64,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 760
  },
  {
    "mark": "Apple",
    "model": "6QE-053",
    "color": "black",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 11.1,
    "coresNumber": 1,
    "usb2": 0,
    "usb3": 4,
    "ram": 16,
    "memory": 512,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 32,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 640
  },
  {
    "mark": "Lenovo",
    "model": "Surface",
    "color": "blue",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 13.3,
    "coresNumber": 4,
    "usb2": 0,
    "usb3": 3,
    "ram": 1,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 4,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 560
  },
  {
    "mark": "MSI",
    "model": "Surface",
    "color": "purple",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 16,
    "usb2": 2,
    "usb3": 4,
    "ram": 64,
    "memory": 8192,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 2,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 420
  },
  {
    "mark": "DEXP",
    "model": "MEDIA CENTER 1574",
    "color": "violet",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 15.6,
    "coresNumber": 2,
    "usb2": 2,
    "usb3": 2,
    "ram": 8,
    "memory": 512,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 1,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 495
  },
  {
    "mark": "Apple",
    "model": "y580",
    "color": "purple",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 17.1,
    "coresNumber": 8,
    "usb2": 0,
    "usb3": 3,
    "ram": 16,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 1,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 840
  },
  {
    "mark": "Apple",
    "model": "GAMER 1748",
    "color": "blue",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 13.7,
    "coresNumber": 16,
    "usb2": 2,
    "usb3": 0,
    "ram": 64,
    "memory": 2048,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 640
  },
  {
    "mark": "Sony",
    "model": "Surface",
    "color": "blue",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 11.3,
    "coresNumber": 8,
    "usb2": 3,
    "usb3": 2,
    "ram": 64,
    "memory": 512,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 16,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 460
  },
  {
    "mark": "Toshiba",
    "model": "Surface",
    "color": "black",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 17.3,
    "coresNumber": 4,
    "usb2": 1,
    "usb3": 0,
    "ram": 2,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 1,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 1280
  },
  {
    "mark": "Sony",
    "model": "GL552VW-DM321T",
    "color": "yellow",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 14,
    "coresNumber": 8,
    "usb2": 1,
    "usb3": 1,
    "ram": 8,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 1,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 530
  },
  {
    "mark": "Sony",
    "model": "GX-700",
    "color": "green",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 11.1,
    "coresNumber": 4,
    "usb2": 0,
    "usb3": 4,
    "ram": 16,
    "memory": 8192,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 4,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 560
  },
  {
    "mark": "Acer",
    "model": "GX-700",
    "color": "violet",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 15.6,
    "coresNumber": 1,
    "usb2": 1,
    "usb3": 3,
    "ram": 32,
    "memory": 1024,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 1,
    "processor": "AMD",
    "operatingSystem": "Linux",
    "price": 780
  },
  {
    "mark": "DEXP",
    "model": "Surface",
    "color": "white",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 17.3,
    "coresNumber": 4,
    "usb2": 0,
    "usb3": 1,
    "ram": 64,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 64,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 725
  },
  {
    "mark": "Apple",
    "model": "GAMER 1748",
    "color": "green",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 13.3,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 0,
    "ram": 1,
    "memory": 256,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 2,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 300
  },
  {
    "mark": "HP",
    "model": "DM036T",
    "color": "black",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 17.3,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 3,
    "ram": 16,
    "memory": 1024,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 2,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 840
  },
  {
    "mark": "Acer",
    "model": "9F4-5",
    "color": "grey",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 1,
    "usb2": 2,
    "usb3": 0,
    "ram": 16,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 32,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 940
  },
  {
    "mark": "Lenovo",
    "model": "Redhost",
    "color": "grey",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 14,
    "coresNumber": 8,
    "usb2": 1,
    "usb3": 3,
    "ram": 8,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 8,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 670
  },
  {
    "mark": "HP",
    "model": "6QE-053",
    "color": "blue",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 11.1,
    "coresNumber": 2,
    "usb2": 1,
    "usb3": 4,
    "ram": 4,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 4,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 760
  },
  {
    "mark": "Acer",
    "model": "EeeBook",
    "color": "white",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 17.1,
    "coresNumber": 8,
    "usb2": 2,
    "usb3": 2,
    "ram": 16,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 1,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 780
  },
  {
    "mark": "MSI",
    "model": "GL552VW-DM321T",
    "color": "yellow",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 8,
    "usb2": 1,
    "usb3": 3,
    "ram": 4,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 2,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 300
  },
  {
    "mark": "Dell",
    "model": "9F4-5",
    "color": "grey",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 15.6,
    "coresNumber": 8,
    "usb2": 2,
    "usb3": 4,
    "ram": 2,
    "memory": 128,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 1,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 850
  },
  {
    "mark": "Dell",
    "model": "Surface",
    "color": "blue",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 11.1,
    "coresNumber": 8,
    "usb2": 3,
    "usb3": 3,
    "ram": 32,
    "memory": 128,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 670
  },
  {
    "mark": "Lenovo",
    "model": "DM036T",
    "color": "violet",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 11.3,
    "coresNumber": 16,
    "usb2": 2,
    "usb3": 4,
    "ram": 4,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 16,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 495
  },
  {
    "mark": "Toshiba",
    "model": "Mac Pro",
    "color": "grey",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 14,
    "coresNumber": 2,
    "usb2": 3,
    "usb3": 3,
    "ram": 2,
    "memory": 128,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 16,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 300
  },
  {
    "mark": "ASUS",
    "model": "IdeaPad",
    "color": "violet",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 17.1,
    "coresNumber": 2,
    "usb2": 1,
    "usb3": 1,
    "ram": 64,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 16,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 920
  },
  {
    "mark": "MSI",
    "model": "6QE-053",
    "color": "violet",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 17.1,
    "coresNumber": 8,
    "usb2": 3,
    "usb3": 3,
    "ram": 16,
    "memory": 8192,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 1,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 780
  },
  {
    "mark": "Toshiba",
    "model": "DM036T",
    "color": "blue",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 17.3,
    "coresNumber": 1,
    "usb2": 3,
    "usb3": 3,
    "ram": 16,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 16,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 840
  },
  {
    "mark": "Apple",
    "model": "6QE-053",
    "color": "purple",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 1,
    "usb2": 1,
    "usb3": 3,
    "ram": 64,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 2,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 1280
  },
  {
    "mark": "DEXP",
    "model": "GL552VW-DM321T",
    "color": "blue",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 2,
    "ram": 16,
    "memory": 8192,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 4,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 1020
  },
  {
    "mark": "Apple",
    "model": "optima",
    "color": "purple",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 15.6,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 4,
    "ram": 16,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 4,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 780
  },
  {
    "mark": "Lenovo",
    "model": "9F4-5",
    "color": "blue",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 11.1,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 2,
    "ram": 4,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 16,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 1280
  },
  {
    "mark": "Apple",
    "model": "MEDIA CENTER 1574",
    "color": "black",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 4,
    "usb2": 3,
    "usb3": 3,
    "ram": 8,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 2,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 510
  },
  {
    "mark": "HP",
    "model": "GAMER 1748",
    "color": "white",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 13.7,
    "coresNumber": 4,
    "usb2": 3,
    "usb3": 4,
    "ram": 64,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 2,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 860
  },
  {
    "mark": "ASUS",
    "model": "optima",
    "color": "green",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 17.1,
    "coresNumber": 16,
    "usb2": 2,
    "usb3": 3,
    "ram": 64,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 2,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 380
  },
  {
    "mark": "Sony",
    "model": "6QE-053",
    "color": "black",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 17.3,
    "coresNumber": 2,
    "usb2": 2,
    "usb3": 0,
    "ram": 2,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 16,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 530
  },
  {
    "mark": "Sony",
    "model": "GL552VW-DM321T",
    "color": "violet",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 2,
    "usb2": 3,
    "usb3": 3,
    "ram": 64,
    "memory": 1024,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 16,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 780
  },
  {
    "mark": "Toshiba",
    "model": "GL552VW-DM321T",
    "color": "grey",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 14,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 4,
    "ram": 8,
    "memory": 128,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 8,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 560
  },
  {
    "mark": "Lenovo",
    "model": "GX-700",
    "color": "grey",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 11.3,
    "coresNumber": 1,
    "usb2": 1,
    "usb3": 4,
    "ram": 16,
    "memory": 8192,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 32,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 940
  },
  {
    "mark": "MSI",
    "model": "DM036T",
    "color": "red",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 18.6,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 4,
    "ram": 8,
    "memory": 8192,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 16,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 560
  },
  {
    "mark": "Acer",
    "model": "MEDIA CENTER 1574",
    "color": "white",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 20.1,
    "coresNumber": 16,
    "usb2": 2,
    "usb3": 1,
    "ram": 64,
    "memory": 8192,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 32,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 840
  },
  {
    "mark": "HP",
    "model": "MEDIA CENTER 1574",
    "color": "red",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 13.3,
    "coresNumber": 16,
    "usb2": 3,
    "usb3": 0,
    "ram": 64,
    "memory": 8192,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 580
  },
  {
    "mark": "HP",
    "model": "GX-700",
    "color": "blue",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 1,
    "ram": 4,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 32,
    "processor": "AMD",
    "operatingSystem": "Linux",
    "price": 850
  },
  {
    "mark": "DEXP",
    "model": "y580",
    "color": "white",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 11.1,
    "coresNumber": 1,
    "usb2": 0,
    "usb3": 1,
    "ram": 64,
    "memory": 4096,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 16,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 300
  },
  {
    "mark": "Sony",
    "model": "Zenbook Pro",
    "color": "red",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 15.6,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 3,
    "ram": 16,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 8,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 670
  },
  {
    "mark": "Dell",
    "model": "Zenbook Pro",
    "color": "purple",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 4,
    "usb2": 3,
    "usb3": 4,
    "ram": 64,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 4,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 1280
  },
  {
    "mark": "Acer",
    "model": "9F4-5",
    "color": "red",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 20.1,
    "coresNumber": 2,
    "usb2": 3,
    "usb3": 4,
    "ram": 4,
    "memory": 8192,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 16,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 840
  },
  {
    "mark": "HP",
    "model": "GX-700",
    "color": "violet",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 17.3,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 0,
    "ram": 8,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 4,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 850
  },
  {
    "mark": "HP",
    "model": "Zenbook Pro",
    "color": "red",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 8,
    "usb2": 0,
    "usb3": 3,
    "ram": 1,
    "memory": 512,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 4,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 300
  },
  {
    "mark": "Toshiba",
    "model": "MEDIA CENTER 1574",
    "color": "yellow",
    "wifi": "802.11c",
    "isLaptop": false,
    "diagonal": 13.3,
    "coresNumber": 2,
    "usb2": 2,
    "usb3": 3,
    "ram": 16,
    "memory": 1024,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 725
  },
  {
    "mark": "Acer",
    "model": "optima",
    "color": "black",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 14,
    "coresNumber": 16,
    "usb2": 3,
    "usb3": 0,
    "ram": 2,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 32,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 420
  },
  {
    "mark": "ASUS",
    "model": "Redhost",
    "color": "white",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 17.3,
    "coresNumber": 16,
    "usb2": 2,
    "usb3": 4,
    "ram": 1,
    "memory": 128,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 2,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 840
  },
  {
    "mark": "Lenovo",
    "model": "DM036T",
    "color": "green",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 14,
    "coresNumber": 8,
    "usb2": 1,
    "usb3": 4,
    "ram": 1,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 64,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 840
  },
  {
    "mark": "Apple",
    "model": "9F4-5",
    "color": "orange",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 18.6,
    "coresNumber": 1,
    "usb2": 0,
    "usb3": 0,
    "ram": 32,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 4,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 460
  },
  {
    "mark": "ASUS",
    "model": "DM036T",
    "color": "green",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 8,
    "usb2": 2,
    "usb3": 3,
    "ram": 64,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 2,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 670
  },
  {
    "mark": "HP",
    "model": "optima",
    "color": "orange",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 18.6,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 3,
    "ram": 64,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 16,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 940
  },
  {
    "mark": "Sony",
    "model": "9F4-5",
    "color": "black",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 1,
    "usb2": 0,
    "usb3": 1,
    "ram": 4,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 32,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 725
  },
  {
    "mark": "ASUS",
    "model": "Mac mini",
    "color": "violet",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 18.6,
    "coresNumber": 1,
    "usb2": 2,
    "usb3": 3,
    "ram": 2,
    "memory": 1024,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 64,
    "processor": "Intel",
    "operatingSystem": "Windows",
    "price": 860
  },
  {
    "mark": "MSI",
    "model": "DM036T",
    "color": "yellow",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 8,
    "usb2": 0,
    "usb3": 1,
    "ram": 64,
    "memory": 2048,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 8,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 850
  },
  {
    "mark": "Toshiba",
    "model": "DM036T",
    "color": "violet",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 15.6,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 2,
    "ram": 8,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 2,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 640
  },
  {
    "mark": "HP",
    "model": "Mac Pro",
    "color": "red",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 13.3,
    "coresNumber": 1,
    "usb2": 2,
    "usb3": 1,
    "ram": 64,
    "memory": 512,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 940
  },
  {
    "mark": "ASUS",
    "model": "MEDIA CENTER 1574",
    "color": "violet",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 17.1,
    "coresNumber": 1,
    "usb2": 0,
    "usb3": 2,
    "ram": 8,
    "memory": 8192,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 8,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 780
  },
  {
    "mark": "HP",
    "model": "GX-700",
    "color": "white",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 11.3,
    "coresNumber": 1,
    "usb2": 1,
    "usb3": 1,
    "ram": 2,
    "memory": 512,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 8,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 860
  },
  {
    "mark": "Apple",
    "model": "DM036T",
    "color": "violet",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 20.1,
    "coresNumber": 8,
    "usb2": 2,
    "usb3": 2,
    "ram": 1,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 4,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 380
  },
  {
    "mark": "Dell",
    "model": "Zenbook Pro",
    "color": "green",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 18.6,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 2,
    "ram": 2,
    "memory": 4096,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 4,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 920
  },
  {
    "mark": "Acer",
    "model": "GL552VW-DM321T",
    "color": "purple",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 20.1,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 3,
    "ram": 64,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 64,
    "processor": "Mac",
    "operatingSystem": "Linux",
    "price": 495
  },
  {
    "mark": "Toshiba",
    "model": "GL552VW-DM321T",
    "color": "black",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 14,
    "coresNumber": 1,
    "usb2": 3,
    "usb3": 4,
    "ram": 8,
    "memory": 4096,
    "videocard": "Intel HD Graphics 4000",
    "videomemory": 32,
    "processor": "Mac",
    "operatingSystem": "Windows",
    "price": 760
  },
  {
    "mark": "DEXP",
    "model": "IdeaPad",
    "color": "yellow",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 14,
    "coresNumber": 1,
    "usb2": 1,
    "usb3": 2,
    "ram": 16,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 32,
    "processor": "AMD",
    "operatingSystem": "Mac OS X",
    "price": 840
  },
  {
    "mark": "Toshiba",
    "model": "GAMER 1748",
    "color": "black",
    "wifi": "802.11a",
    "isLaptop": true,
    "diagonal": 20.1,
    "coresNumber": 16,
    "usb2": 3,
    "usb3": 4,
    "ram": 64,
    "memory": 128,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 32,
    "processor": "Intel",
    "operatingSystem": "Mac OS X",
    "price": 460
  },
  {
    "mark": "Sony",
    "model": "GX-700",
    "color": "orange",
    "wifi": "802.11ac",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 4,
    "usb2": 2,
    "usb3": 3,
    "ram": 64,
    "memory": 1024,
    "videocard": "NVidia GeForce GTX 640",
    "videomemory": 1,
    "processor": "Mac",
    "operatingSystem": "Mac OS X",
    "price": 1500
  },
  {
    "mark": "MSI",
    "model": "optima",
    "color": "purple",
    "wifi": "802.11ac",
    "isLaptop": true,
    "diagonal": 13.3,
    "coresNumber": 2,
    "usb2": 0,
    "usb3": 3,
    "ram": 2,
    "memory": 8192,
    "videocard": "NVidia GeForce GTX 730",
    "videomemory": 1,
    "processor": "Intel",
    "operatingSystem": "Linux",
    "price": 1500
  },
  {
    "mark": "Toshiba",
    "model": "DM036T",
    "color": "purple",
    "wifi": "802.11c",
    "isLaptop": true,
    "diagonal": 13.7,
    "coresNumber": 2,
    "usb2": 2,
    "usb3": 4,
    "ram": 32,
    "memory": 256,
    "videocard": "NVidia GeForce GTX 950",
    "videomemory": 32,
    "processor": "AMD",
    "operatingSystem": "Windows",
    "price": 580
  },
  {
    "mark": "Apple",
    "model": "6QE-053",
    "color": "red",
    "wifi": "802.11a",
    "isLaptop": false,
    "diagonal": 11.3,
    "coresNumber": 8,
    "usb2": 2,
    "usb3": 1,
    "ram": 1,
    "memory": 128,
    "videocard": "Intel HD Graphics 3000",
    "videomemory": 2,
    "processor": "AMD",
    "operatingSystem": "Linux",
    "price": 1500
  }
];
