'use strict';

module.exports = [
  {
    "price": 660,
    "operatingSystem": "Android",
    "diagonal": 5.5,
    "camera": 10,
    "memory": 16,
    "ram": 2,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11a",
    "color": "yellow",
    "model": "Grand Prime",
    "mark": "Nokia"
  },
  {
    "price": 220,
    "operatingSystem": "Android",
    "diagonal": 6,
    "camera": 15,
    "memory": 4,
    "ram": 4,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "P1M",
    "mark": "Huawey"
  },
  {
    "price": 240,
    "operatingSystem": "Android",
    "diagonal": 4.8,
    "camera": 10,
    "memory": 2,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "Light Dual",
    "mark": "Lenovo"
  },
  {
    "price": 480,
    "operatingSystem": "Window Phone",
    "diagonal": 5.5,
    "camera": 13,
    "memory": 64,
    "ram": 4,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "P1M",
    "mark": "Lenovo"
  },
  {
    "price": 480,
    "operatingSystem": "Window Phone",
    "diagonal": 4.2,
    "camera": 18,
    "memory": 32,
    "ram": 8,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11c",
    "color": "purple",
    "model": "Galaxy",
    "mark": "HTC"
  },
  {
    "price": 580,
    "operatingSystem": "iOS",
    "diagonal": 4.7,
    "camera": 8,
    "memory": 8,
    "ram": 2,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11c",
    "color": "white",
    "model": "6s",
    "mark": "iPhone"
  },
  {
    "price": 420,
    "operatingSystem": "Window Phone",
    "diagonal": 6.3,
    "camera": 10,
    "memory": 64,
    "ram": 1,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "Grand Prime",
    "mark": "Huawey"
  },
  {
    "price": 560,
    "operatingSystem": "iOS",
    "diagonal": 4.1,
    "camera": 15,
    "memory": 32,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "black",
    "model": 650,
    "mark": "Huawey"
  },
  {
    "price": 540,
    "operatingSystem": "iOS",
    "diagonal": 5.2,
    "camera": 10,
    "memory": 2,
    "ram": 8,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "5s",
    "mark": "Nokia"
  },
  {
    "price": 500,
    "operatingSystem": "Window Phone",
    "diagonal": 4.8,
    "camera": 12,
    "memory": 32,
    "ram": 4,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11c",
    "color": "white",
    "model": 650,
    "mark": "Huawey"
  },
  {
    "price": 220,
    "operatingSystem": "iOS",
    "diagonal": 4.2,
    "camera": 10,
    "memory": 8,
    "ram": 1,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "purple",
    "model": "Vibe",
    "mark": "iPhone"
  },
  {
    "price": 580,
    "operatingSystem": "iOS",
    "diagonal": 5.7,
    "camera": 13,
    "memory": 4,
    "ram": 8,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": "5s",
    "mark": "Lenovo"
  },
  {
    "price": 800,
    "operatingSystem": "iOS",
    "diagonal": 6,
    "camera": 18,
    "memory": 8,
    "ram": 2,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "black",
    "model": "Galaxy",
    "mark": "HTC"
  },
  {
    "price": 420,
    "operatingSystem": "Window Phone",
    "diagonal": 5.1,
    "camera": 12,
    "memory": 32,
    "ram": 8,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11a",
    "color": "violet",
    "model": "Galaxy",
    "mark": "Sony"
  },
  {
    "price": 450,
    "operatingSystem": "Window Phone",
    "diagonal": 4.1,
    "camera": 15,
    "memory": 2,
    "ram": 4,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "Vibe",
    "mark": "Huawey"
  },
  {
    "price": 450,
    "operatingSystem": "iOS",
    "diagonal": 5,
    "camera": 13,
    "memory": 4,
    "ram": 1,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "P70-A",
    "mark": "Huawey"
  },
  {
    "price": 240,
    "operatingSystem": "Android",
    "diagonal": 5,
    "camera": 12,
    "memory": 32,
    "ram": 4,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11c",
    "color": "orange",
    "model": "MX5",
    "mark": "LG"
  },
  {
    "price": 330,
    "operatingSystem": "Android",
    "diagonal": 4,
    "camera": 5,
    "memory": 16,
    "ram": 2,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11c",
    "color": "red",
    "model": "MX5",
    "mark": "LG"
  },
  {
    "price": 480,
    "operatingSystem": "Window Phone",
    "diagonal": 5.5,
    "camera": 15,
    "memory": 4,
    "ram": 8,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11ac",
    "color": "green",
    "model": "Galaxy",
    "mark": "HTC"
  },
  {
    "price": 450,
    "operatingSystem": "iOS",
    "diagonal": 4.8,
    "camera": 5,
    "memory": 4,
    "ram": 8,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11a",
    "color": "green",
    "model": "Vibe",
    "mark": "iPhone"
  },
  {
    "price": 360,
    "operatingSystem": "iOS",
    "diagonal": 5.7,
    "camera": 15,
    "memory": 4,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11c",
    "color": "white",
    "model": "Light Dual",
    "mark": "Sony"
  },
  {
    "price": 600,
    "operatingSystem": "Android",
    "diagonal": 4.7,
    "camera": 12,
    "memory": 4,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "P70-A",
    "mark": "Lenovo"
  },
  {
    "price": 600,
    "operatingSystem": "Android",
    "diagonal": 5.7,
    "camera": 13,
    "memory": 4,
    "ram": 2,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11a",
    "color": "grey",
    "model": "Vibe",
    "mark": "ZTE"
  },
  {
    "price": 280,
    "operatingSystem": "Android",
    "diagonal": 6.3,
    "camera": 5,
    "memory": 2,
    "ram": 4,
    "coresNumber": 8,
    "gps": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "6s",
    "mark": "Nokia"
  },
  {
    "price": 220,
    "operatingSystem": "iOS",
    "diagonal": 4,
    "camera": 5,
    "memory": 64,
    "ram": 8,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "MX5",
    "mark": "Xaomi"
  },
  {
    "price": 660,
    "operatingSystem": "iOS",
    "diagonal": 5.2,
    "camera": 10,
    "memory": 4,
    "ram": 8,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "Light Dual",
    "mark": "Samsung"
  },
  {
    "price": 580,
    "operatingSystem": "iOS",
    "diagonal": 5,
    "camera": 5,
    "memory": 16,
    "ram": 2,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "6s",
    "mark": "Samsung"
  },
  {
    "price": 480,
    "operatingSystem": "Android",
    "diagonal": 5.3,
    "camera": 13,
    "memory": 4,
    "ram": 1,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11c",
    "color": "red",
    "model": "P70-A",
    "mark": "LG"
  },
  {
    "price": 540,
    "operatingSystem": "Window Phone",
    "diagonal": 4.8,
    "camera": 5,
    "memory": 16,
    "ram": 2,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11c",
    "color": "black",
    "model": "Light Dual",
    "mark": "LG"
  },
  {
    "price": 280,
    "operatingSystem": "iOS",
    "diagonal": 5.5,
    "camera": 10,
    "memory": 2,
    "ram": 1,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "blue",
    "model": "Galaxy",
    "mark": "iPhone"
  },
  {
    "price": 200,
    "operatingSystem": "iOS",
    "diagonal": 5.7,
    "camera": 10,
    "memory": 2,
    "ram": 4,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11c",
    "color": "black",
    "model": "Vibe",
    "mark": "Nokia"
  },
  {
    "price": 300,
    "operatingSystem": "iOS",
    "diagonal": 4,
    "camera": 5,
    "memory": 16,
    "ram": 1,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "6s",
    "mark": "iPhone"
  },
  {
    "price": 710,
    "operatingSystem": "iOS",
    "diagonal": 4.7,
    "camera": 15,
    "memory": 16,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "Galaxy",
    "mark": "iPhone"
  },
  {
    "price": 620,
    "operatingSystem": "Android",
    "diagonal": 5.5,
    "camera": 13,
    "memory": 8,
    "ram": 1,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "yellow",
    "model": "Galaxy",
    "mark": "ZTE"
  },
  {
    "price": 450,
    "operatingSystem": "Window Phone",
    "diagonal": 4.7,
    "camera": 5,
    "memory": 32,
    "ram": 4,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11a",
    "color": "orange",
    "model": "Grand Prime",
    "mark": "ZTE"
  },
  {
    "price": 710,
    "operatingSystem": "Android",
    "diagonal": 4.7,
    "camera": 12,
    "memory": 2,
    "ram": 8,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11a",
    "color": "white",
    "model": "5s",
    "mark": "Xaomi"
  },
  {
    "price": 580,
    "operatingSystem": "Window Phone",
    "diagonal": 5.2,
    "camera": 15,
    "memory": 8,
    "ram": 2,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "green",
    "model": "Galaxy",
    "mark": "Nokia"
  },
  {
    "price": 330,
    "operatingSystem": "Android",
    "diagonal": 5,
    "camera": 5,
    "memory": 64,
    "ram": 8,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "black",
    "model": "Galaxy",
    "mark": "Samsung"
  },
  {
    "price": 390,
    "operatingSystem": "Window Phone",
    "diagonal": 5.3,
    "camera": 12,
    "memory": 64,
    "ram": 1,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11c",
    "color": "white",
    "model": "Galaxy",
    "mark": "Sony"
  },
  {
    "price": 200,
    "operatingSystem": "Window Phone",
    "diagonal": 4.8,
    "camera": 15,
    "memory": 4,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11c",
    "color": "red",
    "model": "Vibe",
    "mark": "Sony"
  },
  {
    "price": 600,
    "operatingSystem": "iOS",
    "diagonal": 6.3,
    "camera": 12,
    "memory": 4,
    "ram": 8,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "MX5",
    "mark": "iPhone"
  },
  {
    "price": 420,
    "operatingSystem": "Window Phone",
    "diagonal": 4.4,
    "camera": 18,
    "memory": 16,
    "ram": 4,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "grey",
    "model": "Grand Prime",
    "mark": "HTC"
  },
  {
    "price": 200,
    "operatingSystem": "iOS",
    "diagonal": 6,
    "camera": 15,
    "memory": 2,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11c",
    "color": "orange",
    "model": 650,
    "mark": "ZTE"
  },
  {
    "price": 800,
    "operatingSystem": "Window Phone",
    "diagonal": 4.1,
    "camera": 10,
    "memory": 2,
    "ram": 4,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "6s",
    "mark": "HTC"
  },
  {
    "price": 280,
    "operatingSystem": "Window Phone",
    "diagonal": 4.7,
    "camera": 10,
    "memory": 4,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11c",
    "color": "green",
    "model": "P70-A",
    "mark": "Samsung"
  },
  {
    "price": 800,
    "operatingSystem": "Window Phone",
    "diagonal": 4.9,
    "camera": 15,
    "memory": 8,
    "ram": 8,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": 650,
    "mark": "LG"
  },
  {
    "price": 390,
    "operatingSystem": "iOS",
    "diagonal": 4.7,
    "camera": 15,
    "memory": 32,
    "ram": 2,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "5s",
    "mark": "ZTE"
  },
  {
    "price": 300,
    "operatingSystem": "Window Phone",
    "diagonal": 4.4,
    "camera": 12,
    "memory": 8,
    "ram": 2,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "Light Dual",
    "mark": "Samsung"
  },
  {
    "price": 480,
    "operatingSystem": "Window Phone",
    "diagonal": 5.3,
    "camera": 10,
    "memory": 8,
    "ram": 2,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11ac",
    "color": "orange",
    "model": "Vibe",
    "mark": "Sony"
  },
  {
    "price": 620,
    "operatingSystem": "Window Phone",
    "diagonal": 4.9,
    "camera": 13,
    "memory": 32,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11c",
    "color": "violet",
    "model": "Grand Prime",
    "mark": "Samsung"
  },
  {
    "price": 540,
    "operatingSystem": "iOS",
    "diagonal": 5,
    "camera": 8,
    "memory": 2,
    "ram": 8,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11a",
    "color": "grey",
    "model": "P70-A",
    "mark": "LG"
  },
  {
    "price": 600,
    "operatingSystem": "Android",
    "diagonal": 5.5,
    "camera": 5,
    "memory": 8,
    "ram": 8,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11a",
    "color": "grey",
    "model": "P1M",
    "mark": "Huawey"
  },
  {
    "price": 660,
    "operatingSystem": "iOS",
    "diagonal": 6.1,
    "camera": 5,
    "memory": 64,
    "ram": 2,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "orange",
    "model": "P70-A",
    "mark": "Huawey"
  },
  {
    "price": 390,
    "operatingSystem": "Android",
    "diagonal": 4.7,
    "camera": 15,
    "memory": 8,
    "ram": 1,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11c",
    "color": "violet",
    "model": "Light Dual",
    "mark": "iPhone"
  },
  {
    "price": 580,
    "operatingSystem": "iOS",
    "diagonal": 4.5,
    "camera": 10,
    "memory": 32,
    "ram": 2,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": 650,
    "mark": "Huawey"
  },
  {
    "price": 420,
    "operatingSystem": "Android",
    "diagonal": 4,
    "camera": 13,
    "memory": 32,
    "ram": 1,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11a",
    "color": "violet",
    "model": "MX5",
    "mark": "LG"
  },
  {
    "price": 600,
    "operatingSystem": "Android",
    "diagonal": 5.5,
    "camera": 8,
    "memory": 4,
    "ram": 8,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11c",
    "color": "orange",
    "model": "Grand Prime",
    "mark": "Nokia"
  },
  {
    "price": 800,
    "operatingSystem": "Android",
    "diagonal": 5.1,
    "camera": 5,
    "memory": 16,
    "ram": 4,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11c",
    "color": "white",
    "model": "P70-A",
    "mark": "Sony"
  },
  {
    "price": 580,
    "operatingSystem": "Android",
    "diagonal": 4.1,
    "camera": 13,
    "memory": 4,
    "ram": 8,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11ac",
    "color": "black",
    "model": "P70-A",
    "mark": "Sony"
  },
  {
    "price": 500,
    "operatingSystem": "Android",
    "diagonal": 4.1,
    "camera": 12,
    "memory": 4,
    "ram": 1,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "Galaxy",
    "mark": "HTC"
  },
  {
    "price": 660,
    "operatingSystem": "iOS",
    "diagonal": 4.9,
    "camera": 10,
    "memory": 2,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11c",
    "color": "grey",
    "model": "6s",
    "mark": "Xaomi"
  },
  {
    "price": 500,
    "operatingSystem": "Android",
    "diagonal": 4.8,
    "camera": 5,
    "memory": 32,
    "ram": 8,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11c",
    "color": "green",
    "model": "Galaxy",
    "mark": "iPhone"
  },
  {
    "price": 300,
    "operatingSystem": "Android",
    "diagonal": 4.9,
    "camera": 10,
    "memory": 2,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "blue",
    "model": "MX5",
    "mark": "Nokia"
  },
  {
    "price": 800,
    "operatingSystem": "Window Phone",
    "diagonal": 4.2,
    "camera": 18,
    "memory": 2,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "Grand Prime",
    "mark": "Huawey"
  },
  {
    "price": 540,
    "operatingSystem": "Android",
    "diagonal": 4.8,
    "camera": 12,
    "memory": 8,
    "ram": 1,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11ac",
    "color": "red",
    "model": "Galaxy",
    "mark": "Xaomi"
  },
  {
    "price": 560,
    "operatingSystem": "Android",
    "diagonal": 4.4,
    "camera": 8,
    "memory": 2,
    "ram": 4,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "6s",
    "mark": "Samsung"
  },
  {
    "price": 260,
    "operatingSystem": "Android",
    "diagonal": 4.8,
    "camera": 15,
    "memory": 32,
    "ram": 4,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "P1M",
    "mark": "Samsung"
  },
  {
    "price": 540,
    "operatingSystem": "iOS",
    "diagonal": 4.2,
    "camera": 8,
    "memory": 2,
    "ram": 8,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": 650,
    "mark": "Huawey"
  },
  {
    "price": 280,
    "operatingSystem": "Window Phone",
    "diagonal": 5.2,
    "camera": 13,
    "memory": 2,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "green",
    "model": "Galaxy",
    "mark": "Huawey"
  },
  {
    "price": 540,
    "operatingSystem": "Window Phone",
    "diagonal": 5,
    "camera": 10,
    "memory": 8,
    "ram": 4,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "black",
    "model": "Light Dual",
    "mark": "Samsung"
  },
  {
    "price": 560,
    "operatingSystem": "Window Phone",
    "diagonal": 4.4,
    "camera": 18,
    "memory": 4,
    "ram": 4,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11c",
    "color": "red",
    "model": "Grand Prime",
    "mark": "Huawey"
  },
  {
    "price": 450,
    "operatingSystem": "iOS",
    "diagonal": 4,
    "camera": 12,
    "memory": 4,
    "ram": 2,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "Light Dual",
    "mark": "Lenovo"
  },
  {
    "price": 600,
    "operatingSystem": "Window Phone",
    "diagonal": 5.1,
    "camera": 10,
    "memory": 16,
    "ram": 2,
    "coresNumber": 2,
    "gps": true,
    "wifi": "802.11a",
    "color": "red",
    "model": "P70-A",
    "mark": "HTC"
  },
  {
    "price": 600,
    "operatingSystem": "Window Phone",
    "diagonal": 6.3,
    "camera": 10,
    "memory": 64,
    "ram": 1,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "5s",
    "mark": "Lenovo"
  },
  {
    "price": 220,
    "operatingSystem": "Window Phone",
    "diagonal": 5,
    "camera": 15,
    "memory": 64,
    "ram": 1,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11a",
    "color": "green",
    "model": "Grand Prime",
    "mark": "Huawey"
  },
  {
    "price": 390,
    "operatingSystem": "Android",
    "diagonal": 4.1,
    "camera": 12,
    "memory": 8,
    "ram": 8,
    "coresNumber": 8,
    "gps": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "Light Dual",
    "mark": "Lenovo"
  },
  {
    "price": 800,
    "operatingSystem": "iOS",
    "diagonal": 5.3,
    "camera": 12,
    "memory": 64,
    "ram": 1,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "Grand Prime",
    "mark": "ZTE"
  },
  {
    "price": 800,
    "operatingSystem": "Android",
    "diagonal": 4.7,
    "camera": 10,
    "memory": 2,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11c",
    "color": "grey",
    "model": 650,
    "mark": "ZTE"
  },
  {
    "price": 660,
    "operatingSystem": "iOS",
    "diagonal": 4,
    "camera": 18,
    "memory": 32,
    "ram": 8,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11ac",
    "color": "white",
    "model": "Grand Prime",
    "mark": "HTC"
  },
  {
    "price": 240,
    "operatingSystem": "Window Phone",
    "diagonal": 4.4,
    "camera": 18,
    "memory": 64,
    "ram": 2,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "Grand Prime",
    "mark": "Huawey"
  },
  {
    "price": 260,
    "operatingSystem": "Window Phone",
    "diagonal": 5.7,
    "camera": 18,
    "memory": 4,
    "ram": 8,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11a",
    "color": "blue",
    "model": "Grand Prime",
    "mark": "iPhone"
  },
  {
    "price": 390,
    "operatingSystem": "Window Phone",
    "diagonal": 4.2,
    "camera": 18,
    "memory": 32,
    "ram": 8,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "5s",
    "mark": "ZTE"
  },
  {
    "price": 480,
    "operatingSystem": "iOS",
    "diagonal": 6.3,
    "camera": 5,
    "memory": 4,
    "ram": 8,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "violet",
    "model": "P1M",
    "mark": "ZTE"
  },
  {
    "price": 730,
    "operatingSystem": "Android",
    "diagonal": 4.8,
    "camera": 5,
    "memory": 8,
    "ram": 2,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "5s",
    "mark": "ZTE"
  },
  {
    "price": 730,
    "operatingSystem": "iOS",
    "diagonal": 5.5,
    "camera": 10,
    "memory": 16,
    "ram": 4,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": 650,
    "mark": "Lenovo"
  },
  {
    "price": 500,
    "operatingSystem": "Window Phone",
    "diagonal": 5.2,
    "camera": 18,
    "memory": 2,
    "ram": 4,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": 650,
    "mark": "Nokia"
  },
  {
    "price": 220,
    "operatingSystem": "iOS",
    "diagonal": 4.8,
    "camera": 15,
    "memory": 4,
    "ram": 8,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "purple",
    "model": "P1M",
    "mark": "iPhone"
  },
  {
    "price": 540,
    "operatingSystem": "Window Phone",
    "diagonal": 5.7,
    "camera": 13,
    "memory": 16,
    "ram": 2,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "violet",
    "model": "P70-A",
    "mark": "ZTE"
  },
  {
    "price": 730,
    "operatingSystem": "Window Phone",
    "diagonal": 4.7,
    "camera": 5,
    "memory": 64,
    "ram": 8,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "violet",
    "model": "P1M",
    "mark": "Sony"
  },
  {
    "price": 420,
    "operatingSystem": "Window Phone",
    "diagonal": 4.8,
    "camera": 18,
    "memory": 16,
    "ram": 1,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11c",
    "color": "orange",
    "model": "Grand Prime",
    "mark": "Nokia"
  },
  {
    "price": 800,
    "operatingSystem": "iOS",
    "diagonal": 4.1,
    "camera": 8,
    "memory": 64,
    "ram": 4,
    "coresNumber": 4,
    "gps": false,
    "wifi": "802.11a",
    "color": "black",
    "model": "Vibe",
    "mark": "LG"
  },
  {
    "price": 500,
    "operatingSystem": "Window Phone",
    "diagonal": 5.1,
    "camera": 18,
    "memory": 4,
    "ram": 4,
    "coresNumber": 4,
    "gps": true,
    "wifi": "802.11a",
    "color": "blue",
    "model": 650,
    "mark": "ZTE"
  },
  {
    "price": 730,
    "operatingSystem": "Window Phone",
    "diagonal": 5.7,
    "camera": 12,
    "memory": 64,
    "ram": 1,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11a",
    "color": "yellow",
    "model": "Vibe",
    "mark": "Huawey"
  },
  {
    "price": 710,
    "operatingSystem": "Android",
    "diagonal": 5.7,
    "camera": 13,
    "memory": 64,
    "ram": 8,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11c",
    "color": "purple",
    "model": 650,
    "mark": "Samsung"
  },
  {
    "price": 800,
    "operatingSystem": "Android",
    "diagonal": 5.7,
    "camera": 12,
    "memory": 32,
    "ram": 1,
    "coresNumber": 1,
    "gps": false,
    "wifi": "802.11a",
    "color": "green",
    "model": "MX5",
    "mark": "Samsung"
  },
  {
    "price": 260,
    "operatingSystem": "iOS",
    "diagonal": 5.7,
    "camera": 12,
    "memory": 4,
    "ram": 1,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11c",
    "color": "white",
    "model": "Grand Prime",
    "mark": "Huawey"
  },
  {
    "price": 500,
    "operatingSystem": "Android",
    "diagonal": 5.3,
    "camera": 13,
    "memory": 64,
    "ram": 1,
    "coresNumber": 8,
    "gps": true,
    "wifi": "802.11c",
    "color": "blue",
    "model": "Vibe",
    "mark": "Lenovo"
  },
  {
    "price": 220,
    "operatingSystem": "iOS",
    "diagonal": 5,
    "camera": 18,
    "memory": 4,
    "ram": 2,
    "coresNumber": 2,
    "gps": false,
    "wifi": "802.11a",
    "color": "yellow",
    "model": "P1M",
    "mark": "Lenovo"
  },
  {
    "price": 800,
    "operatingSystem": "Android",
    "diagonal": 4.7,
    "camera": 12,
    "memory": 32,
    "ram": 8,
    "coresNumber": 1,
    "gps": true,
    "wifi": "802.11a",
    "color": "orange",
    "model": "MX5",
    "mark": "Sony"
  },
  {
    "price": 660,
    "operatingSystem": "Android",
    "diagonal": 6.1,
    "camera": 12,
    "memory": 64,
    "ram": 4,
    "coresNumber": 8,
    "gps": false,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "Grand Prime",
    "mark": "Xaomi"
  },
  {
    "mark": "Nokia",
    "model": "Grand Prime",
    "color": "yellow",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 2,
    "ram": 2,
    "memory": 16,
    "camera": 10,
    "diagonal": 5.5,
    "operatingSystem": "Android",
    "price": 660
  },
  {
    "mark": "Huawey",
    "model": "P1M",
    "color": "grey",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 2,
    "ram": 4,
    "memory": 4,
    "camera": 15,
    "diagonal": 6,
    "operatingSystem": "Android",
    "price": 220
  },
  {
    "mark": "Lenovo",
    "model": "Light Dual",
    "color": "purple",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 2,
    "camera": 10,
    "diagonal": 4.8,
    "operatingSystem": "Android",
    "price": 240
  },
  {
    "mark": "Lenovo",
    "model": "P1M",
    "color": "orange",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 2,
    "ram": 4,
    "memory": 64,
    "camera": 13,
    "diagonal": 5.5,
    "operatingSystem": "Window Phone",
    "price": 480
  },
  {
    "mark": "HTC",
    "model": "Galaxy",
    "color": "purple",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 2,
    "ram": 8,
    "memory": 32,
    "camera": 18,
    "diagonal": 4.2,
    "operatingSystem": "Window Phone",
    "price": 480
  },
  {
    "mark": "iPhone",
    "model": "6s",
    "color": "white",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 4,
    "ram": 2,
    "memory": 8,
    "camera": 8,
    "diagonal": 4.7,
    "operatingSystem": "iOS",
    "price": 580
  },
  {
    "mark": "Huawey",
    "model": "Grand Prime",
    "color": "grey",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 4,
    "ram": 1,
    "memory": 64,
    "camera": 10,
    "diagonal": 6.3,
    "operatingSystem": "Window Phone",
    "price": 420
  },
  {
    "mark": "Huawey",
    "model": 650,
    "color": "black",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 32,
    "camera": 15,
    "diagonal": 4.1,
    "operatingSystem": "iOS",
    "price": 560
  },
  {
    "mark": "Nokia",
    "model": "5s",
    "color": "purple",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 4,
    "ram": 8,
    "memory": 2,
    "camera": 10,
    "diagonal": 5.2,
    "operatingSystem": "iOS",
    "price": 540
  },
  {
    "mark": "Huawey",
    "model": 650,
    "color": "white",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 2,
    "ram": 4,
    "memory": 32,
    "camera": 12,
    "diagonal": 4.8,
    "operatingSystem": "Window Phone",
    "price": 500
  },
  {
    "mark": "iPhone",
    "model": "Vibe",
    "color": "purple",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 1,
    "memory": 8,
    "camera": 10,
    "diagonal": 4.2,
    "operatingSystem": "iOS",
    "price": 220
  },
  {
    "mark": "Lenovo",
    "model": "5s",
    "color": "white",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 8,
    "ram": 8,
    "memory": 4,
    "camera": 13,
    "diagonal": 5.7,
    "operatingSystem": "iOS",
    "price": 580
  },
  {
    "mark": "HTC",
    "model": "Galaxy",
    "color": "black",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 2,
    "memory": 8,
    "camera": 18,
    "diagonal": 6,
    "operatingSystem": "iOS",
    "price": 800
  },
  {
    "mark": "Sony",
    "model": "Galaxy",
    "color": "violet",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 2,
    "ram": 8,
    "memory": 32,
    "camera": 12,
    "diagonal": 5.1,
    "operatingSystem": "Window Phone",
    "price": 420
  },
  {
    "mark": "Huawey",
    "model": "Vibe",
    "color": "grey",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 4,
    "ram": 4,
    "memory": 2,
    "camera": 15,
    "diagonal": 4.1,
    "operatingSystem": "Window Phone",
    "price": 450
  },
  {
    "mark": "Huawey",
    "model": "P70-A",
    "color": "orange",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 1,
    "memory": 4,
    "camera": 13,
    "diagonal": 5,
    "operatingSystem": "iOS",
    "price": 450
  },
  {
    "mark": "LG",
    "model": "MX5",
    "color": "orange",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 2,
    "ram": 4,
    "memory": 32,
    "camera": 12,
    "diagonal": 5,
    "operatingSystem": "Android",
    "price": 240
  },
  {
    "mark": "LG",
    "model": "MX5",
    "color": "red",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 8,
    "ram": 2,
    "memory": 16,
    "camera": 5,
    "diagonal": 4,
    "operatingSystem": "Android",
    "price": 330
  },
  {
    "mark": "HTC",
    "model": "Galaxy",
    "color": "green",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 2,
    "ram": 8,
    "memory": 4,
    "camera": 15,
    "diagonal": 5.5,
    "operatingSystem": "Window Phone",
    "price": 480
  },
  {
    "mark": "iPhone",
    "model": "Vibe",
    "color": "green",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 1,
    "ram": 8,
    "memory": 4,
    "camera": 5,
    "diagonal": 4.8,
    "operatingSystem": "iOS",
    "price": 450
  },
  {
    "mark": "Sony",
    "model": "Light Dual",
    "color": "white",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 4,
    "camera": 15,
    "diagonal": 5.7,
    "operatingSystem": "iOS",
    "price": 360
  },
  {
    "mark": "Lenovo",
    "model": "P70-A",
    "color": "grey",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 4,
    "camera": 12,
    "diagonal": 4.7,
    "operatingSystem": "Android",
    "price": 600
  },
  {
    "mark": "ZTE",
    "model": "Vibe",
    "color": "grey",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 2,
    "ram": 2,
    "memory": 4,
    "camera": 13,
    "diagonal": 5.7,
    "operatingSystem": "Android",
    "price": 600
  },
  {
    "mark": "Nokia",
    "model": "6s",
    "color": "violet",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 8,
    "ram": 4,
    "memory": 2,
    "camera": 5,
    "diagonal": 6.3,
    "operatingSystem": "Android",
    "price": 280
  },
  {
    "mark": "Xaomi",
    "model": "MX5",
    "color": "yellow",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 8,
    "ram": 8,
    "memory": 64,
    "camera": 5,
    "diagonal": 4,
    "operatingSystem": "iOS",
    "price": 220
  },
  {
    "mark": "Samsung",
    "model": "Light Dual",
    "color": "red",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 8,
    "memory": 4,
    "camera": 10,
    "diagonal": 5.2,
    "operatingSystem": "iOS",
    "price": 660
  },
  {
    "mark": "Samsung",
    "model": "6s",
    "color": "grey",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 2,
    "memory": 16,
    "camera": 5,
    "diagonal": 5,
    "operatingSystem": "iOS",
    "price": 580
  },
  {
    "mark": "LG",
    "model": "P70-A",
    "color": "red",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 1,
    "ram": 1,
    "memory": 4,
    "camera": 13,
    "diagonal": 5.3,
    "operatingSystem": "Android",
    "price": 480
  },
  {
    "mark": "LG",
    "model": "Light Dual",
    "color": "black",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 2,
    "ram": 2,
    "memory": 16,
    "camera": 5,
    "diagonal": 4.8,
    "operatingSystem": "Window Phone",
    "price": 540
  },
  {
    "mark": "iPhone",
    "model": "Galaxy",
    "color": "blue",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 1,
    "memory": 2,
    "camera": 10,
    "diagonal": 5.5,
    "operatingSystem": "iOS",
    "price": 280
  },
  {
    "mark": "Nokia",
    "model": "Vibe",
    "color": "black",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 1,
    "ram": 4,
    "memory": 2,
    "camera": 10,
    "diagonal": 5.7,
    "operatingSystem": "iOS",
    "price": 200
  },
  {
    "mark": "iPhone",
    "model": "6s",
    "color": "orange",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 4,
    "ram": 1,
    "memory": 16,
    "camera": 5,
    "diagonal": 4,
    "operatingSystem": "iOS",
    "price": 300
  },
  {
    "mark": "iPhone",
    "model": "Galaxy",
    "color": "purple",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 16,
    "camera": 15,
    "diagonal": 4.7,
    "operatingSystem": "iOS",
    "price": 710
  },
  {
    "mark": "ZTE",
    "model": "Galaxy",
    "color": "yellow",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 1,
    "memory": 8,
    "camera": 13,
    "diagonal": 5.5,
    "operatingSystem": "Android",
    "price": 620
  },
  {
    "mark": "ZTE",
    "model": "Grand Prime",
    "color": "orange",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 1,
    "ram": 4,
    "memory": 32,
    "camera": 5,
    "diagonal": 4.7,
    "operatingSystem": "Window Phone",
    "price": 450
  },
  {
    "mark": "Xaomi",
    "model": "5s",
    "color": "white",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 1,
    "ram": 8,
    "memory": 2,
    "camera": 12,
    "diagonal": 4.7,
    "operatingSystem": "Android",
    "price": 710
  },
  {
    "mark": "Nokia",
    "model": "Galaxy",
    "color": "green",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 2,
    "memory": 8,
    "camera": 15,
    "diagonal": 5.2,
    "operatingSystem": "Window Phone",
    "price": 580
  },
  {
    "mark": "Samsung",
    "model": "Galaxy",
    "color": "black",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 8,
    "memory": 64,
    "camera": 5,
    "diagonal": 5,
    "operatingSystem": "Android",
    "price": 330
  },
  {
    "mark": "Sony",
    "model": "Galaxy",
    "color": "white",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 2,
    "ram": 1,
    "memory": 64,
    "camera": 12,
    "diagonal": 5.3,
    "operatingSystem": "Window Phone",
    "price": 390
  },
  {
    "mark": "Sony",
    "model": "Vibe",
    "color": "red",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 4,
    "camera": 15,
    "diagonal": 4.8,
    "operatingSystem": "Window Phone",
    "price": 200
  },
  {
    "mark": "iPhone",
    "model": "MX5",
    "color": "violet",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 2,
    "ram": 8,
    "memory": 4,
    "camera": 12,
    "diagonal": 6.3,
    "operatingSystem": "iOS",
    "price": 600
  },
  {
    "mark": "HTC",
    "model": "Grand Prime",
    "color": "grey",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 4,
    "memory": 16,
    "camera": 18,
    "diagonal": 4.4,
    "operatingSystem": "Window Phone",
    "price": 420
  },
  {
    "mark": "ZTE",
    "model": 650,
    "color": "orange",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 2,
    "camera": 15,
    "diagonal": 6,
    "operatingSystem": "iOS",
    "price": 200
  },
  {
    "mark": "HTC",
    "model": "6s",
    "color": "black",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 4,
    "ram": 4,
    "memory": 2,
    "camera": 10,
    "diagonal": 4.1,
    "operatingSystem": "Window Phone",
    "price": 800
  },
  {
    "mark": "Samsung",
    "model": "P70-A",
    "color": "green",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 4,
    "camera": 10,
    "diagonal": 4.7,
    "operatingSystem": "Window Phone",
    "price": 280
  },
  {
    "mark": "LG",
    "model": 650,
    "color": "yellow",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 4,
    "ram": 8,
    "memory": 8,
    "camera": 15,
    "diagonal": 4.9,
    "operatingSystem": "Window Phone",
    "price": 800
  },
  {
    "mark": "ZTE",
    "model": "5s",
    "color": "black",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 2,
    "ram": 2,
    "memory": 32,
    "camera": 15,
    "diagonal": 4.7,
    "operatingSystem": "iOS",
    "price": 390
  },
  {
    "mark": "Samsung",
    "model": "Light Dual",
    "color": "purple",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 2,
    "ram": 2,
    "memory": 8,
    "camera": 12,
    "diagonal": 4.4,
    "operatingSystem": "Window Phone",
    "price": 300
  },
  {
    "mark": "Sony",
    "model": "Vibe",
    "color": "orange",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 8,
    "ram": 2,
    "memory": 8,
    "camera": 10,
    "diagonal": 5.3,
    "operatingSystem": "Window Phone",
    "price": 480
  },
  {
    "mark": "Samsung",
    "model": "Grand Prime",
    "color": "violet",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 32,
    "camera": 13,
    "diagonal": 4.9,
    "operatingSystem": "Window Phone",
    "price": 620
  },
  {
    "mark": "LG",
    "model": "P70-A",
    "color": "grey",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 1,
    "ram": 8,
    "memory": 2,
    "camera": 8,
    "diagonal": 5,
    "operatingSystem": "iOS",
    "price": 540
  },
  {
    "mark": "Huawey",
    "model": "P1M",
    "color": "grey",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 2,
    "ram": 8,
    "memory": 8,
    "camera": 5,
    "diagonal": 5.5,
    "operatingSystem": "Android",
    "price": 600
  },
  {
    "mark": "Huawey",
    "model": "P70-A",
    "color": "orange",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 2,
    "memory": 64,
    "camera": 5,
    "diagonal": 6.1,
    "operatingSystem": "iOS",
    "price": 660
  },
  {
    "mark": "iPhone",
    "model": "Light Dual",
    "color": "violet",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 8,
    "ram": 1,
    "memory": 8,
    "camera": 15,
    "diagonal": 4.7,
    "operatingSystem": "Android",
    "price": 390
  },
  {
    "mark": "Huawey",
    "model": 650,
    "color": "grey",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 2,
    "ram": 2,
    "memory": 32,
    "camera": 10,
    "diagonal": 4.5,
    "operatingSystem": "iOS",
    "price": 580
  },
  {
    "mark": "LG",
    "model": "MX5",
    "color": "violet",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 2,
    "ram": 1,
    "memory": 32,
    "camera": 13,
    "diagonal": 4,
    "operatingSystem": "Android",
    "price": 420
  },
  {
    "mark": "Nokia",
    "model": "Grand Prime",
    "color": "orange",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 4,
    "ram": 8,
    "memory": 4,
    "camera": 8,
    "diagonal": 5.5,
    "operatingSystem": "Android",
    "price": 600
  },
  {
    "mark": "Sony",
    "model": "P70-A",
    "color": "white",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 1,
    "ram": 4,
    "memory": 16,
    "camera": 5,
    "diagonal": 5.1,
    "operatingSystem": "Android",
    "price": 800
  },
  {
    "mark": "Sony",
    "model": "P70-A",
    "color": "black",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 1,
    "ram": 8,
    "memory": 4,
    "camera": 13,
    "diagonal": 4.1,
    "operatingSystem": "Android",
    "price": 580
  },
  {
    "mark": "HTC",
    "model": "Galaxy",
    "color": "violet",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 2,
    "ram": 1,
    "memory": 4,
    "camera": 12,
    "diagonal": 4.1,
    "operatingSystem": "Android",
    "price": 500
  },
  {
    "mark": "Xaomi",
    "model": "6s",
    "color": "grey",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 2,
    "camera": 10,
    "diagonal": 4.9,
    "operatingSystem": "iOS",
    "price": 660
  },
  {
    "mark": "iPhone",
    "model": "Galaxy",
    "color": "green",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 2,
    "ram": 8,
    "memory": 32,
    "camera": 5,
    "diagonal": 4.8,
    "operatingSystem": "Android",
    "price": 500
  },
  {
    "mark": "Nokia",
    "model": "MX5",
    "color": "blue",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 2,
    "camera": 10,
    "diagonal": 4.9,
    "operatingSystem": "Android",
    "price": 300
  },
  {
    "mark": "Huawey",
    "model": "Grand Prime",
    "color": "red",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 2,
    "camera": 18,
    "diagonal": 4.2,
    "operatingSystem": "Window Phone",
    "price": 800
  },
  {
    "mark": "Xaomi",
    "model": "Galaxy",
    "color": "red",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 2,
    "ram": 1,
    "memory": 8,
    "camera": 12,
    "diagonal": 4.8,
    "operatingSystem": "Android",
    "price": 540
  },
  {
    "mark": "Samsung",
    "model": "6s",
    "color": "blue",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 2,
    "ram": 4,
    "memory": 2,
    "camera": 8,
    "diagonal": 4.4,
    "operatingSystem": "Android",
    "price": 560
  },
  {
    "mark": "Samsung",
    "model": "P1M",
    "color": "grey",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 2,
    "ram": 4,
    "memory": 32,
    "camera": 15,
    "diagonal": 4.8,
    "operatingSystem": "Android",
    "price": 260
  },
  {
    "mark": "Huawey",
    "model": 650,
    "color": "yellow",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 1,
    "ram": 8,
    "memory": 2,
    "camera": 8,
    "diagonal": 4.2,
    "operatingSystem": "iOS",
    "price": 540
  },
  {
    "mark": "Huawey",
    "model": "Galaxy",
    "color": "green",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 2,
    "camera": 13,
    "diagonal": 5.2,
    "operatingSystem": "Window Phone",
    "price": 280
  },
  {
    "mark": "Samsung",
    "model": "Light Dual",
    "color": "black",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 4,
    "memory": 8,
    "camera": 10,
    "diagonal": 5,
    "operatingSystem": "Window Phone",
    "price": 540
  },
  {
    "mark": "Huawey",
    "model": "Grand Prime",
    "color": "red",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 1,
    "ram": 4,
    "memory": 4,
    "camera": 18,
    "diagonal": 4.4,
    "operatingSystem": "Window Phone",
    "price": 560
  },
  {
    "mark": "Lenovo",
    "model": "Light Dual",
    "color": "orange",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 2,
    "memory": 4,
    "camera": 12,
    "diagonal": 4,
    "operatingSystem": "iOS",
    "price": 450
  },
  {
    "mark": "HTC",
    "model": "P70-A",
    "color": "red",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 2,
    "ram": 2,
    "memory": 16,
    "camera": 10,
    "diagonal": 5.1,
    "operatingSystem": "Window Phone",
    "price": 600
  },
  {
    "mark": "Lenovo",
    "model": "5s",
    "color": "blue",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 2,
    "ram": 1,
    "memory": 64,
    "camera": 10,
    "diagonal": 6.3,
    "operatingSystem": "Window Phone",
    "price": 600
  },
  {
    "mark": "Huawey",
    "model": "Grand Prime",
    "color": "green",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 4,
    "ram": 1,
    "memory": 64,
    "camera": 15,
    "diagonal": 5,
    "operatingSystem": "Window Phone",
    "price": 220
  },
  {
    "mark": "Lenovo",
    "model": "Light Dual",
    "color": "black",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 8,
    "ram": 8,
    "memory": 8,
    "camera": 12,
    "diagonal": 4.1,
    "operatingSystem": "Android",
    "price": 390
  },
  {
    "mark": "ZTE",
    "model": "Grand Prime",
    "color": "violet",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 4,
    "ram": 1,
    "memory": 64,
    "camera": 12,
    "diagonal": 5.3,
    "operatingSystem": "iOS",
    "price": 800
  },
  {
    "mark": "ZTE",
    "model": 650,
    "color": "grey",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 2,
    "camera": 10,
    "diagonal": 4.7,
    "operatingSystem": "Android",
    "price": 800
  },
  {
    "mark": "HTC",
    "model": "Grand Prime",
    "color": "white",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 4,
    "ram": 8,
    "memory": 32,
    "camera": 18,
    "diagonal": 4,
    "operatingSystem": "iOS",
    "price": 660
  },
  {
    "mark": "Huawey",
    "model": "Grand Prime",
    "color": "black",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 4,
    "ram": 2,
    "memory": 64,
    "camera": 18,
    "diagonal": 4.4,
    "operatingSystem": "Window Phone",
    "price": 240
  },
  {
    "mark": "iPhone",
    "model": "Grand Prime",
    "color": "blue",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 1,
    "ram": 8,
    "memory": 4,
    "camera": 18,
    "diagonal": 5.7,
    "operatingSystem": "Window Phone",
    "price": 260
  },
  {
    "mark": "ZTE",
    "model": "5s",
    "color": "red",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 8,
    "memory": 32,
    "camera": 18,
    "diagonal": 4.2,
    "operatingSystem": "Window Phone",
    "price": 390
  },
  {
    "mark": "ZTE",
    "model": "P1M",
    "color": "violet",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 8,
    "memory": 4,
    "camera": 5,
    "diagonal": 6.3,
    "operatingSystem": "iOS",
    "price": 480
  },
  {
    "mark": "ZTE",
    "model": "5s",
    "color": "violet",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 8,
    "ram": 2,
    "memory": 8,
    "camera": 5,
    "diagonal": 4.8,
    "operatingSystem": "Android",
    "price": 730
  },
  {
    "mark": "Lenovo",
    "model": 650,
    "color": "violet",
    "wifi": "802.11ac",
    "gps": true,
    "coresNumber": 1,
    "ram": 4,
    "memory": 16,
    "camera": 10,
    "diagonal": 5.5,
    "operatingSystem": "iOS",
    "price": 730
  },
  {
    "mark": "Nokia",
    "model": 650,
    "color": "white",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 4,
    "ram": 4,
    "memory": 2,
    "camera": 18,
    "diagonal": 5.2,
    "operatingSystem": "Window Phone",
    "price": 500
  },
  {
    "mark": "iPhone",
    "model": "P1M",
    "color": "purple",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 8,
    "memory": 4,
    "camera": 15,
    "diagonal": 4.8,
    "operatingSystem": "iOS",
    "price": 220
  },
  {
    "mark": "ZTE",
    "model": "P70-A",
    "color": "violet",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 2,
    "memory": 16,
    "camera": 13,
    "diagonal": 5.7,
    "operatingSystem": "Window Phone",
    "price": 540
  },
  {
    "mark": "Sony",
    "model": "P1M",
    "color": "violet",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 8,
    "memory": 64,
    "camera": 5,
    "diagonal": 4.7,
    "operatingSystem": "Window Phone",
    "price": 730
  },
  {
    "mark": "Nokia",
    "model": "Grand Prime",
    "color": "orange",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 4,
    "ram": 1,
    "memory": 16,
    "camera": 18,
    "diagonal": 4.8,
    "operatingSystem": "Window Phone",
    "price": 420
  },
  {
    "mark": "LG",
    "model": "Vibe",
    "color": "black",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 4,
    "ram": 4,
    "memory": 64,
    "camera": 8,
    "diagonal": 4.1,
    "operatingSystem": "iOS",
    "price": 800
  },
  {
    "mark": "ZTE",
    "model": 650,
    "color": "blue",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 4,
    "ram": 4,
    "memory": 4,
    "camera": 18,
    "diagonal": 5.1,
    "operatingSystem": "Window Phone",
    "price": 500
  },
  {
    "mark": "Huawey",
    "model": "Vibe",
    "color": "yellow",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 8,
    "ram": 1,
    "memory": 64,
    "camera": 12,
    "diagonal": 5.7,
    "operatingSystem": "Window Phone",
    "price": 730
  },
  {
    "mark": "Samsung",
    "model": 650,
    "color": "purple",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 1,
    "ram": 8,
    "memory": 64,
    "camera": 13,
    "diagonal": 5.7,
    "operatingSystem": "Android",
    "price": 710
  },
  {
    "mark": "Samsung",
    "model": "MX5",
    "color": "green",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 1,
    "ram": 1,
    "memory": 32,
    "camera": 12,
    "diagonal": 5.7,
    "operatingSystem": "Android",
    "price": 800
  },
  {
    "mark": "Huawey",
    "model": "Grand Prime",
    "color": "white",
    "wifi": "802.11c",
    "gps": false,
    "coresNumber": 8,
    "ram": 1,
    "memory": 4,
    "camera": 12,
    "diagonal": 5.7,
    "operatingSystem": "iOS",
    "price": 260
  },
  {
    "mark": "Lenovo",
    "model": "Vibe",
    "color": "blue",
    "wifi": "802.11c",
    "gps": true,
    "coresNumber": 8,
    "ram": 1,
    "memory": 64,
    "camera": 13,
    "diagonal": 5.3,
    "operatingSystem": "Android",
    "price": 500
  },
  {
    "mark": "Lenovo",
    "model": "P1M",
    "color": "yellow",
    "wifi": "802.11a",
    "gps": false,
    "coresNumber": 2,
    "ram": 2,
    "memory": 4,
    "camera": 18,
    "diagonal": 5,
    "operatingSystem": "iOS",
    "price": 220
  },
  {
    "mark": "Sony",
    "model": "MX5",
    "color": "orange",
    "wifi": "802.11a",
    "gps": true,
    "coresNumber": 1,
    "ram": 8,
    "memory": 32,
    "camera": 12,
    "diagonal": 4.7,
    "operatingSystem": "Android",
    "price": 800
  },
  {
    "mark": "Xaomi",
    "model": "Grand Prime",
    "color": "purple",
    "wifi": "802.11ac",
    "gps": false,
    "coresNumber": 8,
    "ram": 4,
    "memory": 64,
    "camera": 12,
    "diagonal": 6.1,
    "operatingSystem": "Android",
    "price": 660
  }
];
