'use strict';

module.exports = [
  {
    "price": 130,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "yellow",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": "111SU",
    "mark": "Epson"
  },
  {
    "price": 160,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "white",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 155,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "violet",
    "model": "Mita FS-1040",
    "mark": "Canon"
  },
  {
    "price": 310,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "red",
    "model": "Mita FS-1040",
    "mark": "HP"
  },
  {
    "price": 210,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 26,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 110,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "L800",
    "mark": "Canon"
  },
  {
    "price": 110,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "red",
    "model": "Mita FS-1020MFP",
    "mark": "Samsung"
  },
  {
    "price": 210,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Samsung"
  },
  {
    "price": 80,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "orange",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 340,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "violet",
    "model": "L800",
    "mark": "HP"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 270,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 37,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "red",
    "model": "L800",
    "mark": "Canon"
  },
  {
    "price": 340,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "black",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Epson"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "white",
    "model": "111SU",
    "mark": "Canon"
  },
  {
    "price": 110,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "111SU",
    "mark": "HP"
  },
  {
    "price": 270,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 25,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "black",
    "model": "Mita FS-1040",
    "mark": "Canon"
  },
  {
    "price": 110,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 22,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "Mita FS-1040",
    "mark": "HP"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 26,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "L800",
    "mark": "HP"
  },
  {
    "price": 187,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "green",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 80,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "white",
    "model": "Mita FS-1020MFP",
    "mark": "Samsung"
  },
  {
    "price": 140,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Samsung"
  },
  {
    "price": 270,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 22,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "blue",
    "model": "111SU",
    "mark": "Canon"
  },
  {
    "price": 220,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "orange",
    "model": "111SU",
    "mark": "Canon"
  },
  {
    "price": 340,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "green",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 270,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "green",
    "model": "L800",
    "mark": "Canon"
  },
  {
    "price": 270,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "L800",
    "mark": "Epson"
  },
  {
    "price": 270,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "grey",
    "model": "111SU",
    "mark": "HP"
  },
  {
    "price": 80,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "orange",
    "model": "Mita FS-1020MFP",
    "mark": "Epson"
  },
  {
    "price": 254,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "blue",
    "model": "L800",
    "mark": "Epson"
  },
  {
    "price": 254,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "yellow",
    "model": "Mita FS-1040",
    "mark": "Epson"
  },
  {
    "price": 220,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "green",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Canon"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 24,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "L800",
    "mark": "Canon"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "violet",
    "model": "L800",
    "mark": "Canon"
  },
  {
    "price": 210,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "red",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 160,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "green",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Canon"
  },
  {
    "price": 155,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Samsung"
  },
  {
    "price": 80,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "black",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Epson"
  },
  {
    "price": 130,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 24,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Samsung"
  },
  {
    "price": 140,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 25,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "green",
    "model": "111SU",
    "mark": "Canon"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "Mita FS-1040",
    "mark": "HP"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "Mita FS-1040",
    "mark": "HP"
  },
  {
    "price": 210,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "white",
    "model": "L800",
    "mark": "Samsung"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 26,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 254,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "red",
    "model": "Mita FS-1040",
    "mark": "Epson"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "black",
    "model": "Mita FS-1040",
    "mark": "Epson"
  },
  {
    "price": 254,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 25,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "green",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 22,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "white",
    "model": "L800",
    "mark": "HP"
  },
  {
    "price": 80,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "yellow",
    "model": "Mita FS-1040",
    "mark": "Samsung"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 25,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "violet",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 110,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "Mita FS-1020MFP",
    "mark": "Epson"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 37,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "red",
    "model": "L800",
    "mark": "Canon"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 37,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "grey",
    "model": "111SU",
    "mark": "HP"
  },
  {
    "price": 210,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 36,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 37,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "orange",
    "model": "Mita FS-1040",
    "mark": "Samsung"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "Mita FS-1040",
    "mark": "Epson"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "Mita FS-1020MFP",
    "mark": "Canon"
  },
  {
    "price": 187,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "Mita FS-1020MFP",
    "mark": "Samsung"
  },
  {
    "price": 130,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 22,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "grey",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Samsung"
  },
  {
    "price": 110,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "red",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 80,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "Mita FS-1040",
    "mark": "Samsung"
  },
  {
    "price": 130,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "black",
    "model": "111SU",
    "mark": "Epson"
  },
  {
    "price": 160,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 36,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "grey",
    "model": "Mita FS-1040",
    "mark": "Canon"
  },
  {
    "price": 340,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "L800",
    "mark": "Samsung"
  },
  {
    "price": 130,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 24,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "black",
    "model": "Mita FS-1020MFP",
    "mark": "Epson"
  },
  {
    "price": 270,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "grey",
    "model": "Mita FS-1020MFP",
    "mark": "Canon"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 24,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": "111SU",
    "mark": "Epson"
  },
  {
    "price": 270,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 25,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "white",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 36,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "violet",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "purple",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 340,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "blue",
    "model": "Mita FS-1040",
    "mark": "Samsung"
  },
  {
    "price": 130,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 37,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "black",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Canon"
  },
  {
    "price": 254,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 36,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "grey",
    "model": "L800",
    "mark": "HP"
  },
  {
    "price": 110,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "blue",
    "model": "111SU",
    "mark": "HP"
  },
  {
    "price": 155,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 22,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "orange",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 220,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 25,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "red",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 130,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "blue",
    "model": "Mita FS-1020MFP",
    "mark": "HP"
  },
  {
    "price": 220,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "violet",
    "model": "Mita FS-1020MFP",
    "mark": "Samsung"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 22,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "white",
    "model": "Mita FS-1040",
    "mark": "Samsung"
  },
  {
    "price": 130,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "green",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Epson"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "purple",
    "model": "L800",
    "mark": "HP"
  },
  {
    "price": 130,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 25,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "Mita FS-1040",
    "mark": "Canon"
  },
  {
    "price": 270,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 22,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11a",
    "color": "orange",
    "model": "111SU",
    "mark": "Epson"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 30,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "green",
    "model": "111SU",
    "mark": "HP"
  },
  {
    "price": 130,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Samsung"
  },
  {
    "price": 155,
    "printTechnology": "laser",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "yellow",
    "model": "Mita FS-1040",
    "mark": "Samsung"
  },
  {
    "price": 220,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 40,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "red",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 160,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "orange",
    "model": "Mita FS-1020MFP",
    "mark": "Samsung"
  },
  {
    "price": 210,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "orange",
    "model": "L800",
    "mark": "Samsung"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 45,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "white",
    "model": "111SU",
    "mark": "Canon"
  },
  {
    "price": 270,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 36,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "white",
    "model": "Mita FS-1020MFP",
    "mark": "Samsung"
  },
  {
    "price": 210,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 42,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "blue",
    "model": "Mita FS-1040",
    "mark": "Canon"
  },
  {
    "price": 110,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "yellow",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 310,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 60,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "violet",
    "model": "Mita FS-1020MFP",
    "mark": "Samsung"
  },
  {
    "price": 254,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 33,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11ac",
    "color": "black",
    "model": "111SU",
    "mark": "Samsung"
  },
  {
    "price": 155,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 24,
    "isBlackWhite": true,
    "isMFP": true,
    "wifi": "802.11a",
    "color": "violet",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "HP"
  },
  {
    "price": 187,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": false,
    "wifi": "802.11ac",
    "color": "green",
    "model": "LaserJet Pro MFP M177fw",
    "mark": "Epson"
  },
  {
    "price": 340,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 23,
    "isBlackWhite": false,
    "isMFP": true,
    "wifi": "802.11c",
    "color": "white",
    "model": "Mita FS-1040",
    "mark": "Samsung"
  },
  {
    "price": 110,
    "printTechnology": "jet",
    "pageVelocityPerMinute": 36,
    "isBlackWhite": true,
    "isMFP": false,
    "wifi": "802.11c",
    "color": "red",
    "model": "111SU",
    "mark": "Epson"
  }
];
